### PR TITLE
test: add test case to pkg/envoy/lds

### LINKED ISSUE #3419: Tests: add tests to pkg/envoy/lds
a) Add test cases for pkg/envoy/lds `NewResponse()`: 

* many error scenarios not covered
* WASM Stats enabled case not covered.
* ingress routes exists scenario not covered

image

b) Add test cases for pkg/envoy/lds `listenerBuilder.getOutboundFilterChainPerUpstream()`.

Several scenarios not covered:

* No upstream service exists
* Retriving protocol to port map failed for a upstream
* Some error returning cases.

image

Ref #1489

### PR DESCRIPTION
**Pull request by allenlsy**
Signed-off-by: Allen Leigh <allenlsy@gmail.com>

**Description**:

Partially fixed #3419.

Added tests to cover this line:

https://github.com/openservicemesh/osm/blob/d68983d98007942f4bb9e419cce691e559b90a6d/pkg/envoy/lds/response.go#L24

Screen Shot 2021-06-01 at 1 39 12 PM

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| Documentation              | [ ] |
| Install                    | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Ingress                    | [ ] |
| Egress                     | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| SMI Policy                 | [ ] |
| Sidecar Injection          | [ ] |
| Security                   | [ ] |
| Upgrade                    | [ ] |
| Tests                      | ✅ |
| CI System                  | [ ] |
| Demo                       | [ ] |
| Performance                | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

No

1. Is this a breaking change?

No

### CODE REVIEW

**Review by jaellio — APPROVED** [review]

File: pkg/envoy/lds/response_test.go [hunk 1]
```diff
@@ -70,6 +70,13 @@ func TestNewResponse(t *testing.T) {
 	assert.NotNil(proxy)
 
 	proxyRegistry := registry.NewProxyRegistry(registry.ExplicitProxyServiceMapper(func(*envoy.Proxy) ([]service.MeshService, error) {
+		return nil, fmt.Errorf("dummy error")
```
Comment (ksubrmnn) [inline pkg/envoy/lds/response_test.go:73]: Can you add a comment here explaining what you're testing

**Review by ksubrmnn — APPROVED** [review]
