### PR TITLE
fix(cli): do not throw error for osm version when no control plane found

### LINKED ISSUE #4427: osm version command should not throw an error when the control plane is not installed
**Bug description**:
`osm version` command returns an error when the control plane is yet to be installed:
```
$ ./osm version
CLI Version: version.Info{Version:"v1.0.0-rc.3", GitCommit:"edb1d4531f350909d3eca77edee61a9f02056bd8", BuildDate:"2022-01-10-19:16"}
Error: Failed to get mesh version: No mesh found in namespace [osm-system]

$ echo $?
1
```

This should not result in an error, instead, I expect the output to be something similar to:
```
$ ./osm version
CLI Version: version.Info{Version:"v1.0.0-rc.3", GitCommit:"edb1d4531f350909d3eca77edee61a9f02056bd8", BuildDate:"2022-01-10-19:16"}
Server Version: No control plane found in namespace osm-system

$ echo $?
0
```

**Affected area (please mark with X where applicable)**:
- CLI Tool                   [X]

### PR DESCRIPTION
**Pull request by jaellio**
**Description**:

If a control plane is not installed in the specified namespace do
not throw an error for `osm version`. Currently, the command
returns an error in this scenario.

Resolves #4427 

```
$ ./osm version
CLI Version: version.Info{Version:"dev", GitCommit:"d9426600787ac77a413fc97601ad6eef420f0e3c", BuildDate:""}
Mesh Version: No control plane found in namespace [osm-system]

$ echo $?
0
```

Signed-off-by: jaellio <jaellio@microsoft.com>

**Testing done**:
- updated unit tests
- manually verified output

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [x] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project? no
    -   Did you notify the maintainers and provide attribution?

2. Is this a breaking change? no

### CODE REVIEW

File: cmd/cli/version_test.go [hunk 1]
```diff
@@ -170,6 +183,19 @@ func TestOutputVersionInfo(t *testing.T) {
...
+				cliVersionInfo: &version.Info{
+					Version:   "v0.0.0",
+					GitCommit: "xxxxxxx",
+					BuildDate: "0000-00-00-00:00",
+				},
+				remoteVersionInfo: nil,
+			},
+			expected:   "CLI Version: version.Info{Version:\"v0.0.0\", GitCommit:\"xxxxxxx\", BuildDate:\"0000-00-00-00:00\"}\n",
+			clientOnly: false,
+		},
```
Comment (snehachhabria) [inline cmd/cli/version_test.go:198]: Could we extend the unit test to cover the expected to be : `Mesh Version: No control plane found in namespace`

**Review by shashankram — APPROVED** [review]

**Review by johnsonshi — APPROVED** [review]

**Review by snehachhabria — APPROVED** [review]
