### PR TITLE
Fix health probe test flakiness

### LINKED ISSUE #5162: Non-determinism in envoy/bootstrap unit test
go test ./pkg/envoy/bootstrap --run TestBuild --count 10

On a 10 second glance, it looks like the order of the probes matters here, and is failing the tests if they're out of order

### PR DESCRIPTION
**Pull request by keithmattix**
Signed-off-by: Keith Mattix II <keithmattix2@gmail.com>

**Description**:
Fix flakiness in health probe tests due to using a map data structure
Fixes #5162 

**Testing done**:
`go test ./pkg/envoy/bootstrap --run TestBuild -count 10`

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [X] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project? no
    -   Did you notify the maintainers and provide attribution? N/A

2. Is this a breaking change? no

3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? N/A

### CODE REVIEW

File: pkg/envoy/bootstrap/config_test.go [hunk 1]
```diff
@@ -382,5 +383,352 @@ static_resources:
         '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
     name: startup_listener
 `
-	assert.Equal(expectedYAML, string(actualYAML))
+
```
Comment (steeling) [inline pkg/envoy/bootstrap/config_test.go:386]: I'd recommend simply sorting the probes when we convert to yaml so that we get a deterministic order.

**Review by steeling — APPROVED** [review]

**Review by jaellio — APPROVED** [review]
