### PR TITLE
pkg/*: address control plane implementation gaps

### LINKED ISSUE #2527: Implement traffic split in permissive mode
Currently, traffic split policies are not applied in permissive mode. With the completion of routes v2 work, we'll be able to apply traffic split policies in permissive mode while still ignoring any SMI traffic access policies.

cc/ @snehachhabria

### LINKED ISSUE #3777: Local cluster endpoints for service with multiple ports are not correctly programmed
**Bug description**:
Local cluster endpoints for a service with multiple ports are not correctly programmed.

Consider the following k8s service :
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookstore
  name: bookstore
  namespace: bookstore
spec:
  ports:
  - name: ssh
    port: 22 # TCP based 
    protocol: TCP
  - name: web
    port: 80 # HTTP based
    protocol: TCP
  selector:
    app: bookstore
  type: ClusterIP
```

The code in https://github.com/openservicemesh/osm/blob/main/pkg/envoy/cds/cluster.go#L129-L152 incorrectly programs both the ports as endpoints for the local cluster corresponding to the `bookstore` service.

This is due to a limitation in the existing implementation where a single cluster is created for a service. This is not correct because a single local cluster cannot proxy traffic meant for different protocol ports to all the ports the same way. The problem with doing so is that in the above example, HTTP traffic will get proxied to a TCP port, and vice versa.

**Proposed fix**:
- Create cluster per service port. Cluster names should change to include the port corresponding to the cluster. If there are multiple ports on the service that are exposed, multiple local clusters must be created per pert. 
- Update the inbound HTTP routes to only reference HTTP based clusters specific to HTTP ports
- Update the inbound TCP route to only reference TCP based clusters specific to TCP ports

**Affected area (please mark with X where applicable)**:
- Control Plane        [X]
- Networking                  [X]

**Expected behavior**:
HTTP traffic should not be proxied to TCP ports, and vice versa. 

**Steps to reproduce the bug (as precisely as possible)**:
1. Create a service with multiple ports (HTTP and TCP)
2. Send HTTP traffic to the service on it's HTTP port

Since the service has a TCP port, the local cluster endpoints will incorrectly include this port.

### PR DESCRIPTION
**Pull request by shashankram**
**Description**:
This change refactors the core control plane components
to address several gaps in the existing implementation.

At a high level, it resolves the following:

1. Traffic to a service with multiple ports is filtered and
   routed correctly based on the port the traffic is directed
   to (#3777). This was previously a blocker for users with
   multiple ports/protocols per k8s service object.

2. Builds mesh traffic policies for LDS/CDS/RDS configs
   inline consistently. This simplifies the code and makes
   it a lot easier to test config generation based on the
   state of the mesh (service, service accounts, SMI policies
   etc.). It also eliminates outbound policy merges that
   are unnecessary. Building config for different envoy configs
   inline will help when OSM moves to an event-driven config
   generation per proxy/group model, where an event can produce
   configuration using a nearly consistent view of the caches.

3. Allows the TargetPort for a service to be different than it's
   Port value. This is common in k8s to allow app authors to
   change the backend port without needing to update their client
   code.

4. Similar to egress, mesh RDS configs are isolated per port to
   avoid conflicts when the same host needs to be routed differently
   per port. This can happen when the same service exposes multiple
   HTTP ports that need to be routed differently.

5. Correctly generates hostnames for a service-port combination that
   clients can use to access the service.

7. Addresses bugs in endpoint discovery when the service has multiple
   ports. Correctly translates a cluster name to a MeshService to be
   able to retrieve its endpoints.

8. Implements SMI TrafficSplit for permissive mode for both HTTP and
   TCP traffic.

9. Removes and simplifies code that is not required, such as the APIs
   to retrieve port:protocol mappings for a service, and other redundant
   APIs.

10. E2e tests and unit tests for various scenarios: multiple ports per
    service, permissive mode traffic split, different TargetPort for
    service Port etc.

To understand this change better, it's important to note the following
fundamental changes made to address the existing implementation issues
noted above.

- A MeshService now carries information on the port, target port and
  protocol associated with the service. The implementation ensures
  the target port is always set for a service with an endpoint. It is
  necessary to disambiguate between the two because k8s allows routing
  traffic to a service whose Port and TargetPort are different. This
  is of significant importance when it comes to filtering and routing
  traffic on the client and server side. A k8s service with multiple
  ports is transposed to multiple MeshService representations within
  the OSM control plane. A MeshService is the source of truth while
  creating filtering and routing configs in Envoy as opposed to a k8s
  service. In other words, filter chains, clusters per service have
  a 1-1 mapping to a MeshService instance.

- RDS mesh inbound and outbound route configurations are built per
  port, similar to egress route configurations. This ensures there
  can be no conflicts when a service/FQDN needs to be routed differently
  based on the port.

- Endpoints for a MeshService is filtered by its TargetPort when set. This
  is required to ensure endpoints not associated with the MeshService are not
  programmed for upstream clusters. This is required to support multiple
  ports per service.

Part of #4052 
Resolves #3777 
Resolves #2527

**Testing done**:
- Existing unit tests and e2e tests
- New unit tests and e2e tests
- Verified [ingress demo with Contour](https://docs.openservicemesh.io/docs/demos/ingress_contour/)

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| Control Plane              | [X] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project? `no`
    -   Did you notify the maintainers and provide attribution?

2. Is this a breaking change? `no`

### CODE REVIEW

File: pkg/catalog/types.go [hunk 1]
```diff
@@ -77,33 +71,20 @@ type MeshCataloger interface {
...
 	// GetKubeController returns the kube controller instance handling the current cluster
 	GetKubeController() k8s.Controller
 
-	// GetServiceHostnames returns the hostnames for this service, based on the locality of the source.
-	GetServiceHostnames(service.MeshService, service.Locality) ([]string, error)
+	// GetOutboundMeshTrafficPolicy returns the outbound mesh traffic policy for the given downstream identity
+	GetOutboundMeshTrafficPolicy(identity.ServiceIdentity) *trafficpolicy.OutboundMeshTrafficPolicy
+
+	// GetInboundMeshTrafficPolicy returns the inbound mesh traffic policy for the given upstream identity and services
+	GetInboundMeshTrafficPolicy(identity.ServiceIdentity, []service.MeshService) *trafficpolicy.InboundMeshTrafficPolicy
```
Comment (draychev) [inline pkg/catalog/types.go:87]: This is fantastic!

File: pkg/envoy/eds/cluster_load_assignment_test.go [hunk 2]
```diff
@@ -30,22 +30,22 @@ func TestNewClusterLoadAssignment(t *testing.T) {
 
 	cla := newClusterLoadAssignment(namespacedServices[0], allServiceEndpoints[namespacedServices[0]])
 	assert.NotNil(cla)
-	assert.Equal(cla.ClusterName, "osm/bookstore-1")
+	assert.Equal(cla.ClusterName, "ns1/bookstore-1|80")
```
Comment (draychev) [inline pkg/envoy/eds/cluster_load_assignment_test.go:33]: So glad to see this!

File: pkg/envoy/eds/response.go [hunk 3]
```diff
@@ -56,6 +53,7 @@ func fulfillEDSRequest(meshCatalog catalog.MeshCataloger, proxy *envoy.Proxy, re
 			log.Error().Err(err).Msgf("Failed listing allowed endpoints for service %s, for proxy identity %s", meshSvc, proxyIdentity)
 			continue
 		}
+		log.Debug().Msgf("FOO Endpoints for upstream service %s for downstream proxy identity %s: %v", cluster, proxyIdentity, endpoints)
```
Comment (draychev) [inline pkg/envoy/eds/response.go:56]: Is this a remnant from a debugging session?

File: pkg/envoy/lds/response_test.go [hunk 4]
```diff
@@ -119,10 +119,16 @@ func TestNewResponse(t *testing.T) {
 	assert.Len(listener.ListenerFilters, 3) // Test has egress policy feature enabled, so 3 filters are expected: OriginalDst, TlsInspector, HttpInspector
 	assert.Equal(listener.ListenerFilters[0].Name, wellknown.OriginalDestination)
 	assert.NotNil(listener.FilterChains)
-	// There are 3 filter chains configured on the outbound-listner based on the configuration:
+	// There are 4 filter chains configured on the outbound-listener based on the configuration:
```
Comment (draychev) [inline pkg/envoy/lds/response_test.go:122]: It seems to me they are still only 3 filter chains.

File: pkg/k8s/types.go [hunk 5]
```diff
@@ -99,15 +99,19 @@ type Controller interface {
 	ListPods() []*corev1.Pod
 
 	// ListServiceIdentitiesForService lists ServiceAccounts associated with the given service
-	ListServiceIdentitiesForService(svc service.MeshService) ([]identity.K8sServiceAccount, error)
+	ListServiceIdentitiesForService(service.MeshService) ([]identity.K8sServiceAccount, error)
 
 	// GetEndpoints returns the endpoints for a given service, if found
-	GetEndpoints(svc service.MeshService) (*corev1.Endpoints, error)
+	GetEndpoints(service.MeshService) (*corev1.Endpoints, error)
```
Comment (draychev) [inline pkg/k8s/types.go:105]: Thanks for the cleanup!

**Review by draychev — APPROVED** [review]
🚢 it!

File: pkg/envoy/lds/response_test.go (hunk 4 above)
Comment (shashankram) [reply pkg/envoy/lds/response_test.go]: Good catch, updated the comment!

File: pkg/envoy/eds/response.go (hunk 3 above)
Comment (shashankram) [reply pkg/envoy/eds/response.go]: Yes, removed the `FOO` string and made this log a `trace` to aid debugging.

File: pkg/catalog/inbound_traffic_policies.go [hunk 6]
```diff
@@ -3,195 +3,198 @@ package catalog
...
+func (mc *MeshCatalog) GetInboundMeshTrafficPolicy(upstreamIdentity identity.ServiceIdentity, upstreamServices []service.MeshService) *trafficpolicy.InboundMeshTrafficPolicy {
+	var trafficMatches []*trafficpolicy.TrafficMatch
+	var clusterConfigs []*trafficpolicy.MeshClusterConfig
+	var trafficTargets []*access.TrafficTarget
+	routeConfigPerPort := make(map[int][]*trafficpolicy.InboundTrafficPolicy)
+
+	permissiveMode := mc.configurator.IsPermissiveTrafficPolicyMode()
+	if !permissiveMode {
+		// Pre-computing the list of TrafficTarget optimizes to avoid repeated
+		// cache lookups for each upstream service.
```
Comment (snehachhabria) [inline pkg/catalog/inbound_traffic_policies.go:36]: 👍

File: pkg/catalog/outbound_traffic_policies.go [hunk 7]
```diff
@@ -145,139 +144,41 @@ func (mc *MeshCatalog) ListOutboundServicesForMulticlusterGateway() []service.Me
 // ListOutboundServicesForIdentity list the services the given service account is allowed to initiate outbound connections to
 // Note: ServiceIdentity must be in the format "name.namespace" [https://github.com/openservicemesh/osm/issues/3188]
 func (mc *MeshCatalog) ListOutboundServicesForIdentity(serviceIdentity identity.ServiceIdentity) []service.MeshService {
-	ident := serviceIdentity.ToK8sServiceAccount()
 	if mc.configurator.IsPermissiveTrafficPolicyMode() {
 		return mc.listMeshServices()
 	}
 
+	ident := serviceIdentity.ToK8sServiceAccount()
```
Comment (snehachhabria) [inline pkg/catalog/outbound_traffic_policies.go:151]:
```suggestion
	svcIndentity := serviceIdentity.ToK8sServiceAccount()
```

File: pkg/catalog/outbound_traffic_policies.go [hunk 8]
```diff
@@ -292,60 +193,27 @@ func (mc *MeshCatalog) getDestinationServicesFromTrafficTarget(t *access.Traffic
...
-}
-
-// ListMeshServicesForIdentity returns a list of services the service with the
-// given identity can communicate with, including apex TrafficSplit services.
-func (mc *MeshCatalog) ListMeshServicesForIdentity(identity identity.ServiceIdentity) []service.MeshService {
-	upstreamServices := mc.ListOutboundServicesForIdentity(identity)
+// listAllowedUpstreamServicesIncludeVirtual returns a list of services the given downstream service identity
+// is authorized to communicate with, including virtual services (traffic split apex) that are not backed by
+// pods.
+func (mc *MeshCatalog) listAllowedUpstreamServicesIncludeVirtual(downstreamIdentity identity.ServiceIdentity) []service.MeshService {
```
Comment (snehachhabria) [inline pkg/catalog/outbound_traffic_policies.go:199]: Could we come up with another name instead of Virtual ? I feel like we are introducing another term that you need to be aware of and its not intuitive,  maybe : 
```suggestion
func (mc *MeshCatalog) listAllowedUpstreamServicesIncludeApex(downstreamIdentity identity.ServiceIdentity) []service.MeshService {
```

File: pkg/envoy/cds/cluster.go [hunk 9]
```diff
@@ -81,30 +59,19 @@ func getUpstreamServiceCluster(downstreamIdentity identity.ServiceIdentity, upst
...
-		remoteCluster.ClusterDiscoveryType = &xds_cluster.Cluster_Type{Type: xds_cluster.Cluster_ORIGINAL_DST}
-		remoteCluster.LbPolicy = xds_cluster.Cluster_CLUSTER_PROVIDED
-	} else {
-		// Configure service discovery based on traffic policies
-		remoteCluster.ClusterDiscoveryType = &xds_cluster.Cluster_Type{Type: xds_cluster.Cluster_EDS}
-		remoteCluster.EdsClusterConfig = &xds_cluster.Cluster_EdsClusterConfig{EdsConfig: envoy.GetADSConfigSource()}
-		remoteCluster.LbPolicy = xds_cluster.Cluster_ROUND_ROBIN
-	}
+	// Configure service discovery based on traffic policies
+	remoteCluster.ClusterDiscoveryType = &xds_cluster.Cluster_Type{Type: xds_cluster.Cluster_EDS}
```
Comment (snehachhabria) [inline pkg/envoy/cds/cluster.go:63]: 👍

File: pkg/envoy/rds/response.go [hunk 10]
```diff
@@ -18,45 +18,60 @@ import (
...
-	routeConfiguration := route.BuildRouteConfiguration(inboundTrafficPolicies, outboundTrafficPolicies, proxy, cfg)
 	var rdsResources []types.Resource
 
-	for _, config := range routeConfiguration {
-		rdsResources = append(rdsResources, config)
+	// ---
+	// Build inbound mesh route configurations. These route configurations allow
+	// the services associated with this proxy to accept traffic from downstream
+	// clients on allowed routes.
+	// Build mesh inbound and outbound HTTP route configurations
```
Comment (snehachhabria) [inline pkg/envoy/rds/response.go:41]:
```suggestion
	// Build mesh inbound HTTP route configurations
```

File: pkg/envoy/xdsutil.go [hunk 11]
```diff
@@ -301,18 +300,6 @@ func ParseEnvoyServiceNodeID(serviceNodeID string) (*PodMetadata, error) {
...
-func GetLocalClusterNameForService(proxyService service.MeshService) string {
-	return GetLocalClusterNameForServiceCluster(proxyService.String())
-}
-
-// GetLocalClusterNameForServiceCluster returns the name of the local cluster for the given service cluster.
-// The local cluster refers to the cluster corresponding to the service the proxy is fronting, accessible over localhost by the proxy.
-func GetLocalClusterNameForServiceCluster(clusterName string) string {
-	return fmt.Sprintf("%s%s", clusterName, localClusterSuffix)
-}
-
```
Comment (snehachhabria) [inline pkg/envoy/xdsutil.go:315]: thanks for cleaning up

File: pkg/service/types.go [hunk 12]
```diff
@@ -28,17 +22,42 @@ const (
...
+	// Port maps to ServicePort.Port in k8s: https://pkg.go.dev/k8s.io/api/core/v1#ServicePort
+	Port uint16
+
+	// TargetPort is the port number on which an application accept traffic directed to this MeshService
+	// This can be different than MeshService.Port in k8s.
+	// TargetPort maps to ServicePort.TargetPort in k8s: https://pkg.go.dev/k8s.io/api/core/v1#ServicePort
+	TargetPort uint16
+
+	// Protocol is the protocol served by the service's port
+	Protocol string
```
Comment (snehachhabria) [inline pkg/service/types.go:45]: This is great, it prevents all the back and forth code of converting MeshService to k8s service in the code

**Review by snehachhabria — APPROVED** [review]
