### PR TITLE
fix(e2e): fix HTTP ingress e2e on non-kind

### LINKED ISSUE #2835: http_ingress_test fails on AKS when OSM already installed.
**Bug description**: http_ingress_test gives the following error when the test is run with the "no-install" flag after OSM v0.8.0-rc.2 is installed on AKS cluster. 

`Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready`
**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- CI System                  [X]

**Expected behavior**: https_ingress_test should pass if OSM is already installed. 

**Steps to reproduce the bug (as precisely as possible)**: Install osm v0.8.0-rc.2 on AKS (default namespace), and then run: `go test ./tests/e2e -test.v -ginkgo.v -ginkgo.progress -test.timeout 60m -installType=NoInstall -ginkgo.focus="allows HTTP ingress traffic"`

**How was OSM installed?**: /bin/osm install

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): v0.8.0-rc.2
- Kubernetes version (use `kubectl version`): 1.18.14
- Size of cluster (number of worker nodes in the cluster): 
- Others:

### PR DESCRIPTION
**Pull request by nojnhuh**
**Description**:
This change updates the HTTP ingress e2e test to only install the nginx
ingress controller service as NodePort on kind clusters and LoadBalancer
elsewhere. On kind, test requests are made against `localhost` and for
other clusters against the load balancer ingress IP or hostname of the
nginx service.

Fixes #2835

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [X]
- CI System              [ ]
- Demo                   [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

### CODE REVIEW

**Review by nshankar13 — APPROVED** [review]

File: tests/e2e/e2e_http_ingress_test.go [hunk 1]
```diff
@@ -54,6 +55,27 @@ var _ = OSMDescribe("HTTP ingress",
 			Expect(Td.WaitForPodsRunningReady(destNs, 60*time.Second, 1)).To(Succeed())
 
 			// Install nginx ingress controller
```
Comment (shashankram) [inline tests/e2e/e2e_http_ingress_test.go:57]: I suggest moving the installation of nginx ingress into a separate helper function so that new ingress tests can reuse the code.

**Review by shashankram — APPROVED** [review]

File: tests/e2e/e2e_http_ingress_test.go (hunk 1 above)
Comment (nojnhuh) [reply tests/e2e/e2e_http_ingress_test.go:57]: Are there other tests that need these same changes right now? That should be easy enough to do once we add another ingress test.

Comment (shashankram) [reply tests/e2e/e2e_http_ingress_test.go:57]: Not right now, but I am certain ingress deployment on Kind vs non-Kind clusters needs to be made reusable across tests.
