### PR TITLE
ref(routesv2): Build inbound routes in routes v2 using proxy service

### LINKED ISSUE #2591: routesV2: Build inbound routes only for the proxy's services
**Bug description**:
With routesV2, inbound routes are being built based on the traffic target as opposed to the services backed by the proxy. This will result in issues because the inbound routes will include other services that belong to the same service account that might not be running on that proxy.

Consider the following example:
- Proxy `X` fronting service `X` running on pod `X` with Service Account `foo`
- Proxy `Y` fronting service `Y` running on pod `Y` with Service Account `foo`

With the current implementation, inbound routes on proxy `X` will have references to service `Y`, just because both proxies share the same service account.

This happens because the inbound RDS routes are built based on the proxy's service account instead of service.
```
func (mc *MeshCatalog) buildInboundPolicies(t *access.TrafficTarget) []*trafficpolicy.InboundTrafficPolicy {
	inboundPolicies := []*trafficpolicy.InboundTrafficPolicy{}

	// fetch services running workloads with destination service account
	destServices, err := mc.getDestinationServicesFromTrafficTarget(t)
```

Inbound routes for 1 service (virtual_host in RDS route) should not have references to services not fronted by the proxy.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [X]
- SMI Traffic Specs Policy   [X]
- SMI Traffic Split Policy   [X]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

### PR DESCRIPTION
**Pull request by snehachhabria**
**Description**:

This PR refactors routes v2 to build inbound routes based on the proxy's
services rather than its service account. This is necessary so that only
routes and clusters for the proxy's service are only programmed.

To make this change the routes v2 api that build both inbound and
outbound routes together is split into two separate api's.

Fixes #2591

Signed-off-by: Sneha Chhabria <snchh@microsoft.com>

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]
- Other                  [X]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? `no`

### CODE REVIEW

File: pkg/catalog/routes.go [hunk 1]
```diff
@@ -63,17 +63,21 @@ func (mc *MeshCatalog) listOutboundTrafficPoliciesForTrafficSplits(sourceNamespa
...
 }
 
-// ListTrafficPoliciesForServiceAccount returns all inbound and outbound traffic policies related to the given service account
-func (mc *MeshCatalog) ListTrafficPoliciesForServiceAccount(sa service.K8sServiceAccount) ([]*trafficpolicy.InboundTrafficPolicy, []*trafficpolicy.OutboundTrafficPolicy, error) {
-	inbound, outbound, err := mc.listPoliciesFromTrafficTargets(sa)
-	if err != nil {
-		return nil, nil, err
-	}
+// ListOutboundTrafficPolicies returns all outbound traffic policies related to the given service account
+func (mc *MeshCatalog) ListOutboundTrafficPolicies(sa service.K8sServiceAccount) []*trafficpolicy.OutboundTrafficPolicy {
```
Comment (shashankram) [inline pkg/catalog/routes.go:67]: For clarity,
```suggestion
func (mc *MeshCatalog) ListOutboundTrafficPolicies(downstreamIdentity service.K8sServiceAccount) []*trafficpolicy.OutboundTrafficPolicy {
```

File: pkg/catalog/routes.go [hunk 2]
```diff
@@ -63,17 +63,21 @@ func (mc *MeshCatalog) listOutboundTrafficPoliciesForTrafficSplits(sourceNamespa
...
 
 	outboundPoliciesFromSplits := mc.listOutboundTrafficPoliciesForTrafficSplits(sa.Namespace)
 	outbound = trafficpolicy.MergeOutboundPolicies(outbound, outboundPoliciesFromSplits...)
 
-	return inbound, outbound, nil
+	return outbound
+}
+
+// ListInboundTrafficPolicies returns all inbound traffic policies related to the given service account and inbound services
+func (mc *MeshCatalog) ListInboundTrafficPolicies(sa service.K8sServiceAccount, inboundSvcs []service.MeshService) []*trafficpolicy.InboundTrafficPolicy {
```
Comment (shashankram) [inline pkg/catalog/routes.go:77]:
```suggestion
func (mc *MeshCatalog) ListInboundTrafficPolicies(upstreamIdentity service.K8sServiceAccount, upstreamServices []service.MeshService) []*trafficpolicy.InboundTrafficPolicy {
```

File: pkg/catalog/routes.go [hunk 3]
```diff
@@ -531,7 +535,7 @@ func (mc *MeshCatalog) getDestinationServicesFromTrafficTarget(t *access.Traffic
 	return destServices, nil
 }
 
-func (mc *MeshCatalog) buildInboundPolicies(t *access.TrafficTarget) []*trafficpolicy.InboundTrafficPolicy {
+func (mc *MeshCatalog) buildInboundPolicies(t *access.TrafficTarget, svc service.MeshService) []*trafficpolicy.InboundTrafficPolicy {
 	inboundPolicies := []*trafficpolicy.InboundTrafficPolicy{}
 
 	// fetch services running workloads with destination service account
```
Comment (shashankram) [inline pkg/catalog/routes.go:541]: Why is `destServices` still being used if the caller is already specifying it?

File: pkg/catalog/types.go [hunk 4]
```diff
@@ -66,11 +66,14 @@ type MeshCataloger interface {
...
-	ListTrafficPoliciesForServiceAccount(service.K8sServiceAccount) ([]*trafficpolicy.InboundTrafficPolicy, []*trafficpolicy.OutboundTrafficPolicy, error)
+	// ListTrafficPoliciesForServiceAccount returns all inbound traffic policies related to the given service account and inbound services
+	ListInboundTrafficPolicies(service.K8sServiceAccount, []service.MeshService) []*trafficpolicy.InboundTrafficPolicy
+
+	// ListTrafficPoliciesForServiceAccount returns all outbound traffic policies related to the given service account
+	ListOutboundTrafficPolicies(service.K8sServiceAccount) []*trafficpolicy.OutboundTrafficPolicy
 
 	// ListPoliciesForPermissiveMode returns all inbound and outbound traffic policies related to the given services
-	ListPoliciesForPermissiveMode(services []service.MeshService) ([]*trafficpolicy.InboundTrafficPolicy, []*trafficpolicy.OutboundTrafficPolicy, error)
+	ListPoliciesForPermissiveMode(services []service.MeshService) ([]*trafficpolicy.InboundTrafficPolicy, []*trafficpolicy.OutboundTrafficPolicy)
```
Comment (shashankram) [inline pkg/catalog/types.go:76]: Please open an issue to not have a separate API for permissive mode, and rather handle it internally in the catalog.

File: pkg/catalog/routes.go (hunk 3 above)
Comment (snehachhabria) [reply pkg/catalog/routes.go:541]: This is temporary due to limitations in the current code, I will be taking it out in a follow up PR

File: pkg/catalog/types.go (hunk 4 above)
Comment (snehachhabria) [reply pkg/catalog/types.go:76]: Issue created : https://github.com/openservicemesh/osm/issues/2598

**Review by shashankram — APPROVED** [review]

File: pkg/envoy/rds/new_response_test.go [hunk 5]
```diff
@@ -34,6 +34,8 @@ func TestNewResponse(t *testing.T) {
 	certSerialNumber := certificate.SerialNumber("123456")
 	testProxy := envoy.NewProxy(certCommonName, certSerialNumber, nil)
 
+	testOutbound := []*trafficpolicy.OutboundTrafficPolicy{}
```
Comment (michelleN) [inline pkg/envoy/rds/new_response_test.go:37]: We should probably have a scenario where there are some outbound traffic policy here and then some assertions below to show we're programming outbound virtual host correctly.

File: pkg/catalog/routes.go [hunk 6]
```diff
@@ -679,34 +682,51 @@ func (mc *MeshCatalog) buildOutboundPolicies(source service.K8sServiceAccount, t
...
-	outboundPolicies := []*trafficpolicy.OutboundTrafficPolicy{}
 
 	for _, t := range mc.meshSpec.ListTrafficTargets() { // loop through all traffic targets
 		if !isValidTrafficTarget(t) {
 			continue
 		}
 
-		if t.Spec.Destination.Name == sa.Name { // found inbound
-			inboundPolicies = trafficpolicy.MergeInboundPolicies(false, inboundPolicies, mc.buildInboundPolicies(t)...)
+		if t.Spec.Destination.Name != upstreamIdentity.Name { // not an inbound policy for service
```
Comment (michelleN) [inline pkg/catalog/routes.go:695]: Where are we now checking the the name in the destination is indeed the upstream identity since the if condition has been deleted?

File: pkg/envoy/rds/new_response_test.go (hunk 5 above)
Comment (michelleN) [inline pkg/envoy/rds/new_response_test.go:37]: we should add a test case here that has some outbound traffic policy and check in the assertions that the correct virtual host is being programmed

**Review by eduser25 — APPROVED** [review]

**Review by michelleN — CHANGES_REQUESTED** [review]

File: pkg/catalog/routes.go (hunk 6 above)
Comment (michelleN) [reply pkg/catalog/routes.go:695]: nvm brain fart

File: pkg/envoy/rds/new_response_test.go (hunk 5 above)
Comment (michelleN) [reply pkg/envoy/rds/new_response_test.go:37]: we can do this in a follow up

**Review by michelleN — APPROVED** [review]

File: pkg/envoy/rds/new_response_test.go (hunk 5 above)
Comment (snehachhabria) [reply pkg/envoy/rds/new_response_test.go:37]: Yup, I have made a note of the same. Will have a PR dedicated to unit tests once we have all the functionality for routes v2
