### PR TITLE
fix(pkg/configurator): fix VWH validateFields() test

### LINKED ISSUE #3078: TestValidateFields is not testing the function properly
**Bug description**:
Unit test for TestValidatefields does not actually check that each reason for denial is in the response's StatusReason

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
Should check that each reason for denial is found in the resp.StatusReason 
**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

### PR DESCRIPTION
**Pull request by shalier**
**Description**:
Resolves #3078

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Demo                   [ ]
- Performance            [ ]
- Other                  [ X]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

### CODE REVIEW

File: pkg/configurator/validating_webhook_test.go [hunk 1]
```diff
@@ -258,9 +258,10 @@ func TestValidateFields(t *testing.T) {
 	assert.Nil(err)
 
 	testCases := []struct {
-		testName  string
-		configMap corev1.ConfigMap
-		expRes    *admissionv1.AdmissionResponse
+		testName   string
+		configMap  corev1.ConfigMap
+		expAllowed bool
```
Comment (shashankram) [inline pkg/configurator/validating_webhook_test.go:263]: Would you mind renaming `exp` to `expect` or `expected`.

File: pkg/configurator/validating_webhook_test.go [hunk 2]
```diff
@@ -258,9 +258,10 @@ func TestValidateFields(t *testing.T) {
 	assert.Nil(err)
 
 	testCases := []struct {
-		testName  string
-		configMap corev1.ConfigMap
-		expRes    *admissionv1.AdmissionResponse
```
Comment (shashankram) [inline pkg/configurator/validating_webhook_test.go:263]: We should continue testing the admission response.

**Review by shashankram — CHANGES_REQUESTED** [review]

File: pkg/configurator/validating_webhook_test.go (hunk 2 above)
Comment (shalier) [reply pkg/configurator/validating_webhook_test.go:263]: Do you mean checking if the AdmissionResponse is created? I removed it because before I was using the AdmissionResponse to check the ReasonForDenial, but that check wasn't actually checking that.

Comment (shashankram) [reply pkg/configurator/validating_webhook_test.go:263]: I am suggesting to keep the `&admissionv1.AdmissionResponse` object in the test case expectation and compare it with the result returned by `validateFields()`. That way, the entire response will be matched for equality which includes the reason as well.

Comment (shalier) [reply pkg/configurator/validating_webhook_test.go:263]: Ok, separated the test cases so that the `&admissionv1.AdmissionResponse` were comparable

File: pkg/configurator/validating_webhook_test.go [hunk 3]
```diff
@@ -358,8 +401,9 @@ func TestValidateFields(t *testing.T) {
 				Result:  &metav1.Status{Reason: ""},
 			}
 			res := whc.validateFields(tc.configMap, resp)
-			assert.Contains(tc.expRes.Result.Status, res.Result.Status)
-			assert.Equal(tc.expRes.Allowed, res.Allowed, res.Result.Reason)
+
+			assert.Equal(tc.expectedResponse.Allowed, res.Allowed)
+			assert.Equal(res.Result.Reason, tc.expectedResponse.Result.Reason)
```
Comment (shashankram) [inline pkg/configurator/validating_webhook_test.go:406]:
```suggestion
			assert.Equal(tc.expectedResponse, res)
```

**Review by shashankram — APPROVED** [review]

**Review by snehachhabria — APPROVED** [review]
