### PR TITLE
GetServiceHostnames: Fix nil pointer dereference

### LINKED ISSUE #3902: Nil pointer deref; osm crash
Scale tests are getting a nil pointer deref at random pod numbers. Seems racy.

Couple of late runs
https://github.com/eduser25/osm/actions/runs/1083058864
https://github.com/eduser25/osm/actions/runs/1083193755
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x19e0ff7]

goroutine 245 [running]:
github.com/openservicemesh/osm/pkg/utils.K8sSvcToMeshSvc(...)
	/home/runner/work/osm/osm/pkg/utils/service.go:14
github.com/openservicemesh/osm/pkg/catalog.(*MeshCatalog).GetServiceHostnames(0xc0007c01b0, 0xc00ba5d810, 0x9, 0xc00ba5d880, 0xd, 0x1, 0x0, 0xc00b3e38c0, 0x5, 0x8, ...)
	/home/runner/work/osm/osm/pkg/catalog/service.go:192 +0x97
github.com/openservicemesh/osm/pkg/catalog.(*MeshCatalog).listOutboundTrafficPoliciesForTrafficSplits(0xc0007c01b0, 0xc00bddfcf7, 0x9, 0xc00f1505c0, 0x5, 0x8)
	/home/runner/work/osm/osm/pkg/catalog/outbound_traffic_policies.go:73 +0x189
github.com/openservicemesh/osm/pkg/catalog.(*MeshCatalog).ListOutboundTrafficPolicies(0xc0007c01b0, 0xc00bddfced, 0x21, 0xc0075adc80, 0x1, 0x1)
	/home/runner/work/osm/osm/pkg/catalog/outbound_traffic_policies.go:29 +0x17c
github.com/openservicemesh/osm/pkg/envoy/rds.NewResponse(0x25b3fb0, 0xc0007c01b0, 0xc006525050, 0xc00f435e80, 0x25b97f0, 0xc0000b6300, 0x259db50, 0xc0003d0d20, 0xc0009c6000, 0xc00f690001, ...)
	/home/runner/work/osm/osm/pkg/envoy/rds/response.go:42 +0x182
github.com/openservicemesh/osm/pkg/envoy/ads.(*Server).getTypeResources(0xc0008ac0c0, 0xc006525050, 0xc00f435e80, 0x2, 0x2, 0x1, 0x2, 0x0)
	/home/runner/work/osm/osm/pkg/envoy/ads/response.go:35 +0x2d2
github.com/openservicemesh/osm/pkg/envoy/ads.(*Server).sendResponse(0xc0008ac0c0, 0xc006525050, 0xc001a8bb20, 0x0, 0x25b97f0, 0xc0000b6300, 0xc00f0e5e80, 0x4, 0x4, 0xc01051ebc0, ...)
	/home/runner/work/osm/osm/pkg/envoy/ads/response.go:78 +0x151
github.com/openservicemesh/osm/pkg/envoy/ads.(*proxyResponseJob).Run(0xc00f0e5ec0)
	/home/runner/work/osm/osm/pkg/envoy/ads/jobs.go:31 +0x8b
github.com/openservicemesh/osm/pkg/workerpool.(*worker).work(0xc0007f9410)
	/home/runner/work/osm/osm/pkg/workerpool/workerpool.go:124 +0x285
created by github.com/openservicemesh/osm/pkg/workerpool.NewWorkerPool
	/home/runner/work/osm/osm/pkg/workerpool/workerpool.go:79 +0x126
```

- OSM version (use `osm version`): Main (7/30/2021)
- Kubernetes version (use `kubectl version`): 1.20
- Size of cluster (number of worker nodes in the cluster): 10 nodes

### PR DESCRIPTION
**Pull request by eduser25**
Under the condition of the service disappearing (or not being
present yet due to informer latency), there was a condition
that could try to dereference a nil pointer.

Fixes #3902

Signed-off-by: Eduard Serra <eduser25@gmail.com>

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?
No
1. Is this a breaking change?
No

### CODE REVIEW

File: pkg/catalog/service.go [hunk 1]
```diff
@@ -189,8 +189,12 @@ func (mc *MeshCatalog) listMeshServices() []service.MeshService {
 // If the service is in the same namespace, it returns the shorthand hostname for the service that does not
 // include its namespace, ex: bookstore, bookstore:80
 func (mc *MeshCatalog) GetServiceHostnames(meshService service.MeshService, locality service.Locality) ([]string, error) {
-	svc := utils.K8sSvcToMeshSvc(mc.kubeController.GetService(meshService))
+	v1svc := mc.kubeController.GetService(meshService)
+	if v1svc == nil {
+		return nil, errors.Errorf("Service %s not found", meshService.String())
+	}
 
+	svc := utils.K8sSvcToMeshSvc(v1svc)
```
Comment (shashankram) [inline pkg/catalog/service.go:197]:
```suggestion
	k8sSvc := mc.kubeController.GetService(meshService)
	if k8sSvc == nil {
		return nil, errors.Errorf("Service %s not found", meshService.String())
	}

	svc := utils.K8sSvcToMeshSvc(k8sSvc)
```

**Review by shashankram — APPROVED** [review]
To avoid other crashes due to similar usage, a nil check needs to be in place in `K8sSvcToMeshSvc()`.

**Review by allenlsy — APPROVED** [review]
