### PR TITLE
fix(meshConfig) : Fix MeshConfig availability to OSM control plane resources

### LINKED ISSUE #3904: osm-injector and osm-crd-converter not able to discover MeshConfig resource
**Bug description**:
Both the osm-crd-converter and osm-injector pods show these messages & errors in the logs:
```
{"level":"warn","component":"configurator","time":"2021-07-30T21:33:55Z","file":"client.go:200","message":"MeshConfig osm-system/osm-mesh-config does not exist. Default config values will be used."}
{"level":"info","component":"osm-injector/main","time":"2021-07-30T21:33:55Z","file":"osm-injector.go:145","message":"Initial MeshConfig osm-mesh-config: {\n    \"sidecar\": {\n        \"resources\": {}\n    },\n    \"traffic\": {\n        \"inboundExternalAuthorization\": {}\n    },\n    \"observability\": {\n        \"tracing\": {}\n    },\n    \"certificate\": {},\n    \"experimental\": {\n        \"multicluster\": {}\n    },\n    \"featureFlags\": {}\n}"}
{"level":"warn","component":"configurator","time":"2021-07-30T21:33:56Z","file":"client.go:200","message":"MeshConfig osm-system/osm-mesh-config does not exist. Default config values will be used."}
{"level":"error","component":"configurator","error":"time: invalid duration \"\"","time":"2021-07-30T21:33:56Z","file":"methods.go:156","message":"Error parsing service certificate validity duration "}
{"level":"warn","component":"configurator","time":"2021-07-30T21:33:56Z","file":"client.go:200","message":"MeshConfig osm-system/osm-mesh-config does not exist. Default config values will be used."}
{"level":"error","component":"configurator","time":"2021-07-30T21:33:56Z","file":"methods.go:167","message":"Invalid key bit size: 0"}
```

Upon further inspection, this is probably occurring because the init-container for the osm-controller is what is creating the MeshConfig object called osm-mesh-config by reading the config map called preset-osm-config. However the osm-controller, injector, and crd-converter all get deployed at the same time which is probably resulting in a timing issue where the injector and crd-converter are trying to read the MeshConfig resource which doesn't exist.

One way to solve this would be have the injector and crd-converter wait until the MeshConfig resource is available.

**Affected area (please mark with X where applicable)**:
- Install                    [ X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
Expect no errors in the osm-injector and crd-converter logs

**Steps to reproduce the bug (as precisely as possible)**:
Run the demo

**How was OSM installed?**:
Using the demo script

**Anything else we need to know?**:
No

**Environment**:
- OSM version (use `osm version`): main @ 65e567a6201910d681165656b1bb21329e4fa93f
- Kubernetes version (use `kubectl version`): v1.21.1
- Size of cluster (number of worker nodes in the cluster): Kind
- Others:

### PR DESCRIPTION
**Pull request by snehachhabria**
**Description**:

The init job to initialize the default mesh config is moved to the osm-bootstrap pod (previously called
crd-converter pod). The osm-controller and osm-injector pod wait on the osm-bootstrap to be up and running.

Fixes #3904

Signed-off-by: Sneha Chhabria <snchh@microsoft.com>

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| Control Plane              | [X] |

**Testing done**:

Manually verified that the following error no longer appears on any of the control plane pods : 

`{"level":"warn","component":"configurator","time":"2021-07-30T21:33:55Z","file":"client.go:200","message":"MeshConfig osm-system/osm-mesh-config does not exist. Default config values will be used."}` 

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project? `no`
    -   Did you notify the maintainers and provide attribution?

2. Is this a breaking change? `no`

### CODE REVIEW

File: cmd/osm-controller-bootstrap/osm-controller-bootstrap.go [hunk 1]
```diff
@@ -33,11 +36,18 @@ import (
...
+	presetMeshConfigName    = "preset-mesh-config"
+	presetMeshConfigJSONKey = "preset-mesh-config.json"
+)
+
 var (
 	verbosity          string
 	osmNamespace       string
 	caBundleSecretName string
 	osmMeshConfigName  string
+	kubeConfigFilePath string
```
Comment (shashankram) [inline cmd/osm-controller-bootstrap/osm-controller-bootstrap.go:50]: This is not required since we use in-cluster config. Let's remove it and other occurrences here.

File: cmd/osm-controller-bootstrap/osm-controller-bootstrap_test.go [hunk 2]
```diff
@@ -55,7 +55,8 @@ func TestCreateDefaultMeshConfig(t *testing.T) {
 	"enableValidatingWebhook": false,
 	"enableIngressBackendPolicy": true,
 	"enableEnvoyActiveHealthChecks": true,
-	"enableSnapshotCacheMode": true
+	"enableSnapshotCacheMode": true,
+	"enableCRDConverter": true
```
Comment (shashankram) [inline cmd/osm-controller-bootstrap/osm-controller-bootstrap_test.go:59]: Let's always enable this? It's no longer optional since MeshConfig and other bootstrap functionality is moved into this pod.

File: pkg/apis/config/v1alpha1/mesh_config.go [hunk 3]
```diff
@@ -200,6 +200,10 @@ type FeatureFlags struct {
 	// service mesh backends.
 	EnableIngressBackendPolicy bool `json:"enableIngressBackendPolicy,omitempty"`
 
+	// EnableCRDConverter defines if a conversion webhook server will be added to osm-controller-bootstrap
+	//  for API version conversions for custom resources.
+	EnableCRDConverter bool `json:"enableCRDConverter,omitempty"`
```
Comment (shashankram) [inline pkg/apis/config/v1alpha1/mesh_config.go:205]: I think we should deprecate this and always have it enabled.

File: cmd/osm-controller-bootstrap/osm-controller-bootstrap_test.go (hunk 2 above)
Comment (snehachhabria) [reply cmd/osm-controller-bootstrap/osm-controller-bootstrap_test.go:59]: I actually kept this to determine if we want to patch the CRDs with the conversion webhook. But I guess its not needed and we can just turn it on by default

**Review by allenlsy — APPROVED** [review]

**Review by shashankram — APPROVED** [review]
