### PR TITLE
pubsub: introduce pubsub chan Unsub(), fix few sync tests

### LINKED ISSUE #2108: flaky test in pkg/smi resulting in panic
**Bug description**:
With the introduction of pubsub, it seems like some tests have become flaky. Noticed a test timeout due to panic from a failed CI run:
https://pipelines.actions.githubusercontent.com/FqYyUlFBwgcC4xlcAlRHSOZjGFqxSg5UdT6unwZ3oA6NkQIoht/_apis/pipelines/1/runs/7625/signedlogcontent/40?urlExpires=2020-11-20T23%3A36%3A04.2685328Z&urlSigningMethod=HMACV1&urlSignature=iYp0HOU21ndbGqh7DtKBp220DqmH2ijHFqwB5ctw8Y8%3D

```
11:29PM INF [SMI Client] Waiting for informers' cache to sync: TrafficSplit, HTTPRouteGroup, TCPRoute, TrafficTarget, Backpressure component=mesh-spec file=client.go:90
11:29PM INF [SMI Client] Cache sync finished for [TrafficSplit HTTPRouteGroup TCPRoute TrafficTarget Backpressure] component=mesh-spec file=client.go:98
11:29PM WRN Channel for provider SMI is full, dropping channel notify traffictarget-deleted  component=kube-controller file=event_handlers.go:61
coverage: 33.1% of statements
panic: test timed out after 2m0s

goroutine 243 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1618 +0xe5
created by time.goFunc
	/opt/hostedtoolcache/go/1.15.5/x64/src/time/sleep.go:167 +0x45

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0xc0000e7380, 0x17f264e, 0x7, 0x189d610, 0x497d26)
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1169 +0x2da
testing.runTests.func1(0xc0000e7200)
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1439 +0x78
testing.tRunner(0xc0000e7200, 0xc0000cbda8)
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1123 +0xef
testing.runTests(0xc00048ffa0, 0x24994a0, 0x1, 0x1, 0xbfe6324e53e90eb9, 0x1bf191e44f, 0x24d3ec0, 0x40f5b0)
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1437 +0x2fe
testing.(*M).Run(0xc000247280, 0x0)
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1345 +0x1eb
main.main()
	_testmain.go:99 +0x1c5
```

```
2020-11-20T23:31:05.6008534Z goroutine 234 [select]:
2020-11-20T23:31:05.6009439Z k8s.io/client-go/tools/cache.(*processorListener).pop(0xc000247d00)
2020-11-20T23:31:05.6011145Z 	/home/runner/go/pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/shared_informer.go:709 +0x157
2020-11-20T23:31:05.6012045Z k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0000d3250, 0xc000552520)
2020-11-20T23:31:05.6013010Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:73 +0x51
2020-11-20T23:31:05.6013944Z created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
2020-11-20T23:31:05.6015153Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:71 +0x65
2020-11-20T23:31:05.6015941Z FAIL	github.com/openservicemesh/osm/pkg/smi	120.058s
2020-11-20T23:31:05.6016544Z === RUN   TestAllEqual
```

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- CI System                  [ ]

### PR DESCRIPTION
**Pull request by eduser25**
- Introduces Unsub() to pubsub
- adds a Unsub() test
- moves few tests to use pubsub and not read from individual channels

fixes #2108

- Control Plane          [X]
- Tests                  [X]
----

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

### CODE REVIEW

File: pkg/kubernetes/client_test.go [hunk 1]
```diff
@@ -142,6 +142,7 @@ var _ = Describe("Test Namespace KubeController Methods", func() {
 			serviceChannel := events.GetPubSubInstance().Subscribe(announcements.ServiceAdded,
 				announcements.ServiceDeleted,
 				announcements.ServiceUpdated)
+			defer events.GetPubSubInstance().Close(serviceChannel)
```
Comment (shashankram) [inline pkg/kubernetes/client_test.go:145]: What's the reason for this? Is it to reduce the number of zombie goroutines?
Ideally, the reader never closes the chan, its the writer that initiates the close.

File: pkg/kubernetes/events/event_pubsub.go [hunk 2]
```diff
@@ -36,6 +36,33 @@ func (c *osmPubsub) Publish(message PubSubMessage) {
...
+			_, ok := <-unsubChan
+			if !ok {
+				// Channel closed from pubsub
+				break
+			}
+		}
+		syncCh <- struct{}{}
+	}()
+
+	<-syncCh
```
Comment (shashankram) [inline pkg/kubernetes/events/event_pubsub.go:63]: Since the goroutine + `syncCh` is implementing a synchronous close, why can't this be done inline without a goroutine to close the `unsubChan`?

**Review by shashankram — DISMISSED** [review]

File: pkg/kubernetes/events/event_pubsub.go (hunk 2 above)
Comment (eduser25) [reply pkg/kubernetes/events/event_pubsub.go:63]: Discussed offline, different goroutine on  required by impl of library in use

File: pkg/kubernetes/client_test.go (hunk 1 above)
Comment (eduser25) [reply pkg/kubernetes/client_test.go:145]: discussed offline, reader still needs a way to tell pubsub to stop publishing on that channel and release it from it's tentacles as a close on reader side doesn't seem to trigger a release of it on the pubsub backend side.

**Review by shashankram — DISMISSED** [review]

File: pkg/kubernetes/events/event_pubsub.go [hunk 3]
```diff
@@ -36,6 +36,29 @@ func (c *osmPubsub) Publish(message PubSubMessage) {
...
+// It is synchronized, upon exit the channel is guaranteed to be both
+// unsubbed to all topics and closed.
+// This is a necessary step to guarantee garbage collection
+func (c *osmPubsub) Unsub(unsubChan chan interface{}) {
+	// implementation has several requirements (including different goroutine context)
+	// https://github.com/cskr/pubsub/blob/v1.0.2/pubsub.go#L102
+
+	syncCh := make(chan struct{})
+	go func() {
+		// This should close the channel on the pubsub backend
```
Comment (draychev) [inline pkg/kubernetes/events/event_pubsub.go:49]:
```suggestion
		// This will close the channel on the pubsub backend
```

File: pkg/kubernetes/events/event_pubsub.go [hunk 4]
```diff
@@ -36,6 +36,29 @@ func (c *osmPubsub) Publish(message PubSubMessage) {
 	c.pSub.Pub(message, message.AnnouncementType.String())
 }
 
+// Unsub is the Unsub implementation for PubSub.
+// It is synchronized, upon exit the channel is guaranteed to be both
+// unsubbed to all topics and closed.
+// This is a necessary step to guarantee garbage collection
```
Comment (draychev) [inline pkg/kubernetes/events/event_pubsub.go:42]: At what point in the lifecycle of the controller will this be used? I see that this is needed for garbage collection, but when will it be used, by who, and why?

**Review by draychev — COMMENTED** [review]
What's the use case for Unsub?
Would it make sense to spell out the entire word?

File: pkg/kubernetes/events/event_pubsub.go (hunk 4 above)
Comment (eduser25) [reply pkg/kubernetes/events/event_pubsub.go:42]: > At what point in the lifecycle of the controller will this be used?
None currently. It's a good observation, none of the used objects are freed during the lifetime of the controller.
> when will it be used, by who, and why?
This will be immediately used by unit tests. If we don't release the channels on the pubsub backend, they are still hold and subscribed to the relevant topics accross different unit tests contexts.
Most of all, I think it's a relevant API to provide. There might be instances/parts of the code that we might have the need to release a certain pubsub resource, and we must be able to do it properly without leaking or leaving stuff on the pubsub backend.

Comment (draychev) [reply pkg/kubernetes/events/event_pubsub.go:42]: Thanks for the explanation!  Might be good to drop a comment for clarity. LGTM

**Review by draychev — APPROVED** [review]

**Review by shashankram — APPROVED** [review]
