### PR TITLE
fix(envoy): add keep-alive time to detect sidecar disconnections

### LINKED ISSUE #5149: Set sidecar keep alive
https://github.com/envoyproxy/envoy/issues/6323

We’ve seen customer issues where a sidecar disconnects from the control plane irregularly but thinks it’s still connected, resulting in certificates expiring and requests failing. 

We should also see if the snapshot cache enables keep Alives so we can detect disconnections on the server side. 

This is not verified as the cause of the issue but my leading theory. 

https://github.com/envoyproxy/envoy/issues/6323

### PR DESCRIPTION
**Pull request by SanyaKochhar**
Signed-off-by: Sanya Kochhar <kochhars@microsoft.com>

**Description**: Defines a 60s keep-alive time after which probes will start being sent to check if a sidecar is still connected to the control plane. Previously this defaulted to 2 hours

Resolves #5149

**Testing done**:

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| Control Plane              | [x] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project? no
    -   Did you notify the maintainers and provide attribution? no

2. Is this a breaking change? no

3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? n/a

### CODE REVIEW

File: pkg/envoy/bootstrap/config.go [hunk 1]
```diff
@@ -278,6 +278,11 @@ func (b *Builder) Build() (*xds_bootstrap.Bootstrap, error) {
 							},
 						},
 					},
+					UpstreamConnectionOptions: &xds_cluster.UpstreamConnectionOptions{
+						TcpKeepalive: &xds_core.TcpKeepalive{
+							KeepaliveTime: uint32(60),
```
Comment (SanyaKochhar) [inline pkg/envoy/bootstrap/config.go:283]: @steeling we are additionally able to define the keepalive `probes` and `interval` values, does this seem necessary? We haven't defined these for grpc because go's grpc pkg doesn't have these options. If not they will default as follows:

image

File: pkg/envoy/bootstrap/config.go [hunk 2]
```diff
@@ -278,6 +279,11 @@ func (b *Builder) Build() (*xds_bootstrap.Bootstrap, error) {
 							},
 						},
 					},
+					UpstreamConnectionOptions: &xds_cluster.UpstreamConnectionOptions{
```
Comment (steeling) [inline pkg/envoy/bootstrap/config.go:282]: so reading the defaults for the other values present here we have:

* 60s of no activity before sending a keep-alive
* 9 failed probes before terminating
* 75s between probes

that gives us 660s, or 11 minutes before we disconnect, which feels too long. I'd recommend we bring this down to 5 probes and 5 seconds, which gives us 80s to terminate which is much better.

Comment (SanyaKochhar) [reply pkg/envoy/bootstrap/config.go:282]: That sounds reasonable. Did you mean 5 second interval or 5 second before the first probe goes out?

Comment (steeling) [reply pkg/envoy/bootstrap/config.go:282]: 5s interval

**Review by steeling — APPROVED** [review]

**Review by keithmattix — APPROVED** [review]

**Comment by steeling** [comment]
there's a flaky test that was recently fixed, can you rebase against main?
