### PR TITLE
Use kubernetes hostnames to match against root service in a traffic split

### LINKED ISSUE #1245: Clients making HTTP requests with port number can't access services
**Bug description**:
Currently the control plane does not program service ports while configuring L7 host header based routes in envoy. This means clients specifying port numbers in HTTP requests will not match against L7 HTTP routes, ex. `GET http://foo.bar.svc.cluster.local:9090`. While specifying ports is optional, clients that specify ports will break after the service mesh is installed. OSM should program service ports with hostnames in addition to hostnames without ports.

**Affected area (please mark with X where applicable)**:
- [ ] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [ X] Envoy Control Plane
- [ ] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] Tests
- [ ] CI System

**Expected behavior**:
Client should be able to specify port numbers in HTTP requests (ex. with non standard ports)

**Steps to reproduce the bug (as precisely as possible)**:
Make HTTP requests with port numbers, ex.  `GET http://foo.bar.svc.cluster.local:9090`

**How was OSM installed?**: `./demo/run-osm-demo.sh`

**Anything else we need to know?**: n/a

**Environment**:
- OSM version (use `osm version`): Version: 0.0.1; Commit: 9bc0a4b; Date: 2020-07-27-15:41

### PR DESCRIPTION
**Pull request by shashankram**
When clients make HTTP requests to the root service (spec.service)
in the SMI split policy, the requests could be directed to a specific
port. If the destination service is using ports other than 80, then
clients will make HTTP requests by specifying the port.
Ex. GET http://bookstore.default.svc.cluster.local:9090 to access
a bookstore service in the default namespace running on port 9090.

The above scenarios would result in the port being included
as a part of the host header in HTTP requests, which will not
match against the L7 HTTP rules OSM configures because OSM does not
currently program different combinations of the root service's
hostnames. This change allows clients to be able to make HTTP
requests using kubernetes hostnames for a root service. This
is similar to how hostnames are configured for permissive mode
and when no traffic split policy is specified, with the difference
being the hostnames point to the root service in a traffic split.

This change does not affect no-split and permissive mode scenarios,
nor does it change the routing logic. It only makes it possible for
clients to use kubernetes DNS names associated with the root service
as a part of HTTP requests, 
ex. http://bookstore.default.svc.cluster.local:9090, http://bookstore.default, 
http://bookstore.default.svc:9090 etc.

Resolves #1245

### CODE REVIEW

File: pkg/catalog/routes.go [hunk 1]
```diff
@@ -130,6 +127,11 @@ func (mc *MeshCatalog) GetWeightedClusterForService(svc service.MeshService) (se
 	return getDefaultWeightedClusterForService(svc), nil
 }
 
+// hostnamesTostr returns a comma separated string of hostnames from the list
+func hostnamesTostr(hostnames []string) string {
+	return strings.Join(hostnames, ",")
+}
+
 // GetHostnamesForService returns the hostnames for a service
 func (mc *MeshCatalog) GetHostnamesForService(meshService service.MeshService) (string, error) {
```
Comment (michelleN) [inline pkg/catalog/routes.go:136]: should we rename this `GetHostnamesandPortsforService`?
or maybe we could document this in a comment. was unclear to me that the ports were also being extracted at first.

**Comment by shashankram** [comment]
> Thank you for this change. Could we change up the ports in the demo services so that we can test this in CI?

Will update the demo to incorporate this scenario.

File: pkg/catalog/routes.go (hunk 1 above)
Comment (shashankram) [reply pkg/catalog/routes.go:136]: Comment is more appropriate since port can be part of the hostname.
