### PR TITLE
fix(hostHeaders) : updating host headers configuration on envoy

### LINKED ISSUE #3283: Application traffic's host header should not be rewritten while configuring routes
**Bug description**:
There is an issue with how the routes are built in `pkg/route/route_config.go`, where the host headers in the application traffic are rewritten. Change https://github.com/openservicemesh/osm/pull/3151 introduced the following:
https://github.com/openservicemesh/osm/blob/120e362e1ad834164cb4f93b040e9518f234e4d7/pkg/envoy/route/route_config.go#L190-L192

The original application traffic's host headers should not be rewritten based on input policies, but rather just configured as header matchers.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

### PR DESCRIPTION
**Pull request by snehachhabria**
**Description**:

This commit removed host rewite and adds a header match when host header
is provided via SMI

Fixes #3283

Signed-off-by: Sneha Chhabria <snchh@microsoft.com>

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Demo                   [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? `no`

### CODE REVIEW

File: pkg/envoy/route/route_config.go [hunk 1]
```diff
@@ -52,6 +52,9 @@ const (
 
 	// httpHostHeader is the name of the HTTP host header
 	httpHostHeader = "host"
```
Comment (shashankram) [inline pkg/envoy/route/route_config.go:54]: let's rename this to `hostHeaderKey` and clarify in the comment that this key is used to specify the HTTP Host header in the `HTTPRouteMatch.Headers`

File: pkg/envoy/route/route_config.go [hunk 2]
```diff
@@ -52,6 +52,9 @@ const (
...
+
+	// authorityHeaderKey is the key of the header for HTTP methods
```
Comment (shashankram) [inline pkg/envoy/route/route_config.go:56]:
```suggestion
	// authorityHeaderKey is the key corresponding to the HTTP Host/Authority header programmed as a header matcher in an Envoy route
```

File: pkg/envoy/route/route_config.go [hunk 3]
```diff
@@ -50,8 +50,11 @@ const (
 	// methodHeaderKey is the key of the header for HTTP methods
 	methodHeaderKey = ":method"
 
-	// httpHostHeader is the name of the HTTP host header
-	httpHostHeader = "host"
+	// httpHostHeaderKey is the name of the HTTP host header in HTTPRouteMatch.Headers, specified via SMI
```
Comment (shashankram) [inline pkg/envoy/route/route_config.go:53]: Remove SMI, this is also applicable to ingress and permissive mode.

**Review by shashankram — APPROVED** [review]

**Review by draychev — APPROVED** [review]
