### PR TITLE
fix(injector): Add config to handle non-HTTP health probes

### LINKED ISSUE #2515: Bug in Liveness/Readiness rewriting for HTTPS probes
**Bug description**:

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [x ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

Liveness/Readiness rewriting results in working probes.

**Steps to reproduce the bug (as precisely as possible)**

Original probe definitions:
```
livenessProbe:
  httpGet:
    path: /status
    scheme: HTTPS
    port: 25555
  initialDelaySeconds: 10
readinessProbe:
  failureThreshold: 7
  httpGet:
    path: /status
    scheme: HTTPS
    port: 25555
```

Rewritten probe definitions:

```
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /osm-liveness-probe
    port: 15901
    scheme: HTTPS
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 7
  httpGet:
    path: /osm-readiness-probe
    port: 15902
    scheme: HTTPS
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
```

Result:
```
Readiness probe failed: Get "https://172.18.0.4:15902/osm-readiness-probe": http: server gave HTTP response to HTTPS client
Liveness probe failed: Get "https://172.18.0.4:15901/osm-liveness-probe": http: server gave HTTP response to HTTPS client
```

**How was OSM installed?**: `bin/osm install --enable-permissive-traffic-policy`

**Anything else we need to know?**:

My guess is that the probe listener is only configured for HTTP, but my envoy knowledge is not that deep.
https://github.com/openservicemesh/osm/blob/ef3366531807908a77b3dadd9c3acb921c680b6f/pkg/injector/envoy_config_health_probes.go#L83

**Environment**:
- OSM version (use `osm version`): `Version: dev; Commit: c8636620211127d23a6208ee79687e5dffec296d; Date: 2021-02-08-10:49`
- Kubernetes version (use `kubectl version`): 
  ```
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Size of cluster (number of worker nodes in the cluster): Minikube (1)
- Others:

### PR DESCRIPTION
**Pull request by nojnhuh**
**Description**:
This change modifies the injector to add different configuration to
handle health probes depending on whether the probe is implemented with
HTTP or HTTPS. HTTP probes continue to work through Envoy's HTTP
connection manager. HTTPS will use Envoy's TCP proxy filter instead.

No functional changes to HTTP probes.

Fixes #2515

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [X]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Demo                   [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

### CODE REVIEW

File: pkg/injector/health_probes.go [hunk 1]
```diff
@@ -20,8 +20,9 @@ const (
 var errNoMatchingPort = errors.New("no matching port")
 
 type healthProbe struct {
-	path string
-	port int32
+	path   string
+	port   int32
+	isHTTP bool
```
Comment (shashankram) [inline pkg/injector/health_probes.go:25]: This struct needs comments. I get the code but it might not be obvious to everyone what to expect for each probe protocol.

**Review by shashankram — APPROVED** [review]

**Review by snehachhabria — APPROVED** [review]

File: pkg/injector/health_probes.go (hunk 1 above)
Comment (nojnhuh) [reply pkg/injector/health_probes.go:28]: I added a comment for the `isHTTP` field. I think path and port are self-explanatory.
