### PR TITLE
ref: collapse pkg/policy into k8s Client

### LINKED ISSUE #4863: Push all k8s clients into a layer of clients
We currently have ~5 flavors of kubernetes clients:

* k8s.Controller
* generated "controller" clients for our CRD's
* A large informerCollection type
* a `kube.Client`
* kubernetes.Interface

Instead, we should leverage "layers" of clients, such that our business logic is only aware of 1 layer. This might looks like:

```go
// K8sAPIClient is an abstraction of the K8s API. It has inputs of OSM objects and returns OSM objects.
// It performs the translations, and makes calls to the underlying K8sClient.
type K8sInfraClient struct {
   client K8sClient
}

// K8sClient is aware of k8s types, and has inputs/outputs of k8s objects. It may leverage the informer cache
type K8sClient struct {
   informerCollection
}
```

As we do this, no functions should accept a client object just to make a call to that client. It should only be accepted for dependency injection. An example of this includes `GetKubernetesServerVersionNumber`. Instead, this should be called `GetServerVersionNumber`, and be a method on a k8s client.

This improves our ability to decouple from k8s, and leverage interfaces. Please take a look at the [guiding principles section](https://docs.google.com/document/d/1L_u-XlVU8Fog-uFS3Uf0O2nz8IArQy82cd6Npxm038Y/edit#) for how we can better leverage interfaces.

The new layer for access to these clients will be:

1. MeshCatalog
    a) Contains business logic for constructing the trafficpolicy types
    b) Has no concept of anything related to K8s
    c) Has an embedded compute.Interface
2. The compute.Interface
   a) Only accepts/returns non-k8s type objects. (The exception to this is custom objects where we do not have an analogous OSM type
   b) Performs translations to/from k8s type objects
   c) There may be multiple instances of this, which is how we can interface outside of k8s.
3. The k8s.Client
   a) Basic Get/Set/Update to kubernetes API
   c) Maintains the informer cache
   d) Has a client for each k8s kind
   e) Is only aware of k8s types, is not aware of OSM types

Some nice results:
1. Eventually the MeshCatalog will only contain business logic, so its interface can go away, and any mocks can supply a mock compute.Interface to a real MeshCatalog instance. This will improve our testing of business logic in the MeshCatalog.
2. With the combination of the Builder pattern, which reduces the need for the mesh catalog, and the potential deconstruction of trafficpolicy types, the mesh catalog may be able to be removed completely. This direction should become more clear in the future.

> 

> contains business logic

### PR DESCRIPTION
**Pull request by allenlsy**
Signed-off-by: Allen Leigh <allenlsy@gmail.com>

**Description**:

Partially resolve [#4933](https://github.com/openservicemesh/osm/issues/4933)

Move functions from policy client into k8s client. The only exception is `DetectIngressBackendConflicts()` in the policy package, which is used in by CLI when checking IngressBackend conflicts.

**Testing done**:

Unit test

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| Other                      | [X] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

No

2. Is this a breaking change?

No

3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)?

No

### CODE REVIEW

File: pkg/catalog/catalog.go [hunk 1]
```diff
@@ -5,15 +5,15 @@ import (
...
 	"github.com/openservicemesh/osm/pkg/messaging"
-	"github.com/openservicemesh/osm/pkg/policy"
 	"github.com/openservicemesh/osm/pkg/smi"
 	"github.com/openservicemesh/osm/pkg/ticker"
 )
 
 // NewMeshCatalog creates a new service catalog
 func NewMeshCatalog(meshSpec smi.MeshSpec, certManager *certificate.Manager,
-	policyController policy.Controller, stop <-chan struct{},
+	policyController k8s.PassthroughInterface, stop <-chan struct{},
```
Comment (steeling) [inline pkg/catalog/catalog.go:16]: this is already present on the compute.Interface, so no need to store it twice.

File: pkg/catalog/ingress_test.go [hunk 2]
```diff
@@ -390,7 +390,7 @@ func TestGetIngressTrafficPolicy(t *testing.T) {
 			defer mockCtrl.Finish()
 
 			mockProvider := compute.NewMockInterface(mockCtrl)
-			mockPolicyController := policy.NewMockController(mockCtrl)
+			mockPolicyController := k8s.NewMockController(mockCtrl)
```
Comment (steeling) [inline pkg/catalog/ingress_test.go:393]: let's place the mocked methods on the mockProvider

File: pkg/k8s/client.go [hunk 3]
```diff
@@ -58,6 +58,18 @@ func NewClient(osmNamespace, meshConfigName string, informerCollection *osminfor
 		informerInitHandlerMap[informer]()
 	}
 
+	shouldObserve := func(obj interface{}) bool {
```
Comment (steeling) [inline pkg/k8s/client.go:61]: let's remove these calls here, and add the the event handlers to the informer's `With*` methods

**Comment by allenlsy** [comment]
ping @openservicemesh/osm-maintainers

File: pkg/k8s/client.go (hunk 3 above)
Comment (allenlsy) [reply pkg/k8s/client.go:61]: Can you clarify the idea?

File: pkg/catalog/egress.go [hunk 4]
```diff
@@ -136,8 +136,8 @@ func (mc *MeshCatalog) getUpstreamTrafficSettingForEgress(egressPolicy *policyv1
 				Namespace: egressPolicy.Namespace,
 				Name:      match.Name,
 			}
-			upstreamtrafficSetting := mc.policyController.GetUpstreamTrafficSetting(
-				policy.UpstreamTrafficSettingGetOpt{NamespacedName: &namespacedName})
+			upstreamtrafficSetting := mc.Interface.GetUpstreamTrafficSetting(
+				k8s.UpstreamTrafficSettingGetOpt{NamespacedName: &namespacedName})
```
Comment (jsturtevant) [inline pkg/catalog/egress.go:140]: It's surprising to see the k8s pkg imported into this package.  My understanding was cataglog shouldn't know about k8s?  

Is this option parameter in the wrong place?

File: pkg/catalog/egress.go [hunk 5]
```diff
@@ -35,7 +35,7 @@ func (mc *MeshCatalog) GetEgressTrafficPolicy(serviceIdentity identity.ServiceId
 	var trafficMatches []*trafficpolicy.TrafficMatch
 	var clusterConfigs []*trafficpolicy.EgressClusterConfig
 	portToRouteConfigMap := make(map[int][]*trafficpolicy.EgressHTTPRouteConfig)
-	egressResources := mc.policyController.ListEgressPoliciesForSourceIdentity(serviceIdentity.ToK8sServiceAccount())
+	egressResources := mc.Interface.ListEgressPoliciesForSourceIdentity(serviceIdentity.ToK8sServiceAccount())
```
Comment (jsturtevant) [inline pkg/catalog/egress.go:38]: may not be appropriate in this PR but it would be clear if it was `mc.ComputeInterface`

File: pkg/catalog/types.go [hunk 6]
```diff
@@ -25,10 +24,6 @@ type MeshCatalog struct {
 	compute.Interface
```
Comment (keithmattix) [inline pkg/catalog/types.go:24]: It's not a part of this PR (and it seems like this PR largely avoids this pitfall by explicitly calling out `MeshCatalog.Interface`), but embedding this interface seems to imply a tighter coupling between MeshCatalog and a `compute.Interface` than desired IMO. Interface embedding is already discouraged/prohibited in Uber's [style guide](https://github.com/uber-go/guide/blob/master/style.md#avoid-embedding-types-in-public-structs), and it's just confusing here. In my mind, a `MeshCatalog` has a dependency on a `compute.Interface` it is not itself a `compute.Interface` like embedding may imply. /cc @steeling for some possible context

File: pkg/k8s/client.go (hunk 3 above)
Comment (keithmattix) [reply pkg/k8s/client.go]: I actually don't think these event handlers belong in the With* methods; this code seems to be a correct usage of AddEventHandler

File: pkg/k8s/types.go [hunk 7]
```diff
@@ -70,6 +70,11 @@ const (
 	MeshRootCertificate InformerKey = "MeshRootCertificate"
 )
 
+const (
+	// kindSvcAccount is the ServiceAccount kind
+	kindSvcAccount = "ServiceAccount"
```
Comment (keithmattix) [inline pkg/k8s/types.go:75]: Are there multiple serviceAccount kinds?

File: pkg/validator/server.go [hunk 8]
```diff
@@ -32,7 +32,7 @@ type validatingWebhookServer struct {
 }
 
 // NewValidatingWebhook returns a validatingWebhookServer with the defaultValidators that were previously registered.
-func NewValidatingWebhook(ctx context.Context, webhookConfigName, osmNamespace, osmVersion, meshName string, enableReconciler, validateTrafficTarget bool, certManager *certificate.Manager, kubeClient kubernetes.Interface, policyClient policy.Controller) error {
+func NewValidatingWebhook(ctx context.Context, webhookConfigName, osmNamespace, osmVersion, meshName string, enableReconciler, validateTrafficTarget bool, certManager *certificate.Manager, kubeClient kubernetes.Interface, policyClient k8s.PassthroughInterface) error {
```
Comment (keithmattix) [inline pkg/validator/server.go:35]: Just for posterity: this is a valid use of the passthrough interface because the validatingwebhook concept is Kubernetes specific.

**Review by keithmattix — COMMENTED** [review]
LGTM!

**Review by keithmattix — APPROVED** [review]
Lol, I meant to approve earlier

File: pkg/catalog/egress.go (hunk 4 above)
Comment (allenlsy) [reply pkg/catalog/egress.go:140]: Great point. I agree that `UpstreamTrafficSettingGetOpt` should remain in the policy package

File: pkg/k8s/types.go (hunk 7 above)
Comment (allenlsy) [reply pkg/k8s/types.go:75]: No. I actually don't get the question.

File: pkg/catalog/egress.go (hunk 5 above)
Comment (allenlsy) [reply pkg/catalog/egress.go:38]: Agree but it's better to be addressed in a separate PR.

File: pkg/k8s/types.go (hunk 7 above)
Comment (keithmattix) [reply pkg/k8s/types.go:75]: Usually, with a const grouping like you have here:
```go
const (
...
) 
```
each of the consts declared represent various options of a common type/concept. Looking again, I'm guessing this const is just here to deduplicate the string "ServiceAccount"?

File: pkg/k8s/client.go (hunk 3 above)
Comment (steeling) [reply pkg/k8s/client.go]: sorry i was mistaken ,its' actually in the k8s.client init* methods. take a look at PR https://github.com/openservicemesh/osm/pull/5006 or other instances in the k8/client.go file.

File: pkg/catalog/egress.go (hunk 4 above)
Comment (steeling) [reply pkg/catalog/egress.go:140]: I might suggest the following:

1. place the entire `GetUpstreamTrafficSetting` method in compute/client.
2. Add 2 new methods to k8s.Client: `GetUpstreamTrafficSetting` (takes a name and namespace, no options), and `ListUpstreamTrafficSetting`
3. Break up the `GetUpstreamTrafficSetting` into 3 methods (all in compute.Client), one for each option. The options pattern isn't very well suited here, since combining/permuting options is meaningless.

The final result of all of these changes will be:

1. k8s/client.go: Is merged with the informer package, and contains simple CRUD operations for K8s objects
2. compute.Client, abstracts over the k8s.Client, and provides some logic for retrieving OSMs domain objects
3. MeshCatalog contains higher level methods for combining multiple objects to generate OSM domain objects (may eventually get merged with compute.Client

File: cmd/osm-controller/osm-controller.go [hunk 9]
```diff
@@ -254,7 +250,7 @@ func main() {
 		events.GenericEventRecorder().FatalEvent(err, events.InitializationError, "Error initializing ADS server")
 	}
 
-	if err := validator.NewValidatingWebhook(ctx, validatorWebhookConfigName, osmNamespace, osmVersion, meshName, enableReconciler, validateTrafficTarget, certManager, kubeClient, policyController); err != nil {
+	if err := validator.NewValidatingWebhook(ctx, validatorWebhookConfigName, osmNamespace, osmVersion, meshName, enableReconciler, validateTrafficTarget, certManager, kubeClient, k8sClient); err != nil {
```
[the remark this answers is not in the document]
Comment (allenlsy) [reply cmd/osm-controller/osm-controller.go:252]: I think https://github.com/openservicemesh/osm/issues/4863 fixes the issue you mentioned.

**Comment by steeling** [comment]
> ping @openservicemesh/osm-maintainers

recommend taking it out of draft if its ready for review

**Comment by allenlsy** [comment]
> > ping @openservicemesh/osm-maintainers
> 
> recommend taking it out of draft if its ready for review

Will mark it as ready once the tests are passed.

File: pkg/catalog/egress.go (hunk 5 above)
Comment (steeling) [reply pkg/catalog/egress.go:37]: the issue is the stutter of `compute.ComputeInterface`. 

Whatever we decide, this is an embedded interface, so we can simply call `mc.ListEgressPoliciesForSourceIdentity`. This is useful, because a caller outside of the meshCatalog package doesn't really need to know which one has the responsbility

File: pkg/catalog/types.go (hunk 6 above)
Comment (steeling) [reply pkg/catalog/types.go:24]: Personally, I disagree with Uber's conclusion on embedding interface. Although it might be something to take a harder look at, I think it has its places.

For us here, I think there's a good chance the meshcatalog and compute.Client eventually get merged. Embedding the interface allows abstracting the methods in compute.Interface, such that the response.go files don't need to know which layer of the domain they are accessing.

In fact, I recommend we remove `meshCatalog.Interface.<MethodCall>`, and directly call the method from meshCatalog. As we deconstruct some of the meshcatalog calls it will make for less changes.

* This gets heavy into opinions, so only providing mine as a reference point :)

File: pkg/catalog/egress.go (hunk 4 above)
Comment (allenlsy) [reply pkg/catalog/egress.go]: Update:

1. `UpstreamTrafficSettingGetOpt` is removed.
2. `GetUpstreamTrafficSetting()` is split into 3 methods, one for each option. 

> compute.Client, abstracts over the k8s.Client, and provides some logic for retrieving OSMs domain objects

Do you mean compute.Client abstracts over kube.Client? Currently k8s.Client has no direct connection with compute.Client.

File: pkg/validator/server.go (hunk 8 above)
Comment (jaellio) [reply pkg/validator/server.go:35]: Could you clarify the significance of the passthrough interface? I thought the interface was for methods that were not specific to kubernetes.

Also, should `policyClient` be updated to a more generic name since the interface has methods for more than just the policy resources?

Comment (steeling) [reply pkg/validator/server.go:35]: Ya I agree, it should probably either be the raw k8s.Client, or a meshCatalog, or compute.Interface

Comment (keithmattix) [reply pkg/validator/server.go:35]: Maybe I'm misunderstanding the passthrough interface then; I thought it was for deliberate abstraction leaking in specific cases. Regardless, I do agree the variable should be renamed

File: pkg/catalog/egress.go (hunk 4 above)
Comment (steeling) [reply pkg/catalog/egress.go]: the compute.Client has an embedded k8s.KubeController (which is a k8s.Client object)

File: pkg/catalog/types.go (hunk 6 above)
Comment (steeling) [reply pkg/catalog/types.go:24]: https://github.com/openservicemesh/osm/issues/4863 has the full description

**Review by steeling — APPROVED** [review]

File: pkg/k8s/client.go [hunk 10]
```diff
@@ -463,3 +484,150 @@ func (c *Client) GetMeshConfig() configv1alpha2.MeshConfig {
 func (c *Client) GetOSMNamespace() string {
 	return c.osmNamespace
 }
+
+// ListEgressPoliciesForSourceIdentity lists the Egress policies for the given source identity based on service accounts
+func (c *Client) ListEgressPoliciesForSourceIdentity(source identity.K8sServiceAccount) []*policyv1alpha1.Egress {
```
[the remark this answers is not in the document]
Comment (allenlsy) [reply pkg/k8s/client.go:489]: Egress policy, IngressBackend etc. are OSM/SMI terminologies. I think they are not part of compute.Interface as they are not Kubernetes native.

I will update the method names

[the remark this answers is not in the document]
Comment (allenlsy) [reply pkg/k8s/client.go:489]: For the 3 `GetUpstreamTrafficSettingBy<Type>()` methods, I don't find a better way to name them. They are split from the original `GetUpstreamTrafficSetting()` method. Do you have any suggestion?

[the remark this answers is not in the document]
Comment (steeling) [reply pkg/k8s/client.go:489]: They are being queried from Kubernetes though. The interface is to the control plane of where they are housed. 

So it would looks like this:

in compute/kube/client.go, are all the methods that are defined here.

In k8s/client.go, you have: `ListEgressPolicies`, which just calls list on the informer.

Right now there's logic in k8s, which makes k8s aware of OSM primitives and mappings. The k8s package will have simple CRUD based methods (get, delete, update, create, list), and nothing more. Happy to sync if you'd like

File: pkg/validator/server.go (hunk 8 above)
Comment (keithmattix) [reply pkg/validator/server.go:35]: Oh, that wasn't my intent. I was trying to convey that I think this is a good, intended use of the passthrough interface because it's fine to let abstractions leak into validatingWebhook logic because validatingwebhook logic is explicitly a Kubernetes concept

File: pkg/k8s/client.go [hunk 11]
```diff
@@ -468,3 +489,99 @@ func (c *Client) GetMeshConfig() configv1alpha2.MeshConfig {
...
+			continue
+		}
+		policies = append(policies, egressPolicy)
+	}
+
+	return policies
+}
+
+// GetIngressBackendPolicy returns the IngressBackend policy for the given backend MeshService
+func (c *Client) GetIngressBackendPolicy(namespace, svcName string, targetPort int) *policyv1alpha1.IngressBackend {
```
Comment (steeling) [inline pkg/k8s/client.go:509]: I would just remove this get.. technically we don't really have a get, so the get can be moved up into the compute/client, ie:


```
GetIngressBackendPolicyByService -> calls k8s.ListIngressBackendPolicy, and filters appropriately.
```

The rule of thumb is that Gets should be by just name/namespace. Any other fields are a filter on a list

File: pkg/k8s/client.go [hunk 12]
```diff
@@ -468,3 +489,99 @@ func (c *Client) GetMeshConfig() configv1alpha2.MeshConfig {
...
+		}
+
+		settings = append(settings, setting)
+	}
+
+	return settings
+}
+
+// GetUpstreamTrafficSettingByNamespace returns the UpstreamTrafficSetting resources with matching namespaced name
+func (c *Client) GetUpstreamTrafficSettingByKey(key string) *policyv1alpha1.UpstreamTrafficSetting {
```
Comment (steeling) [inline pkg/k8s/client.go:581]: super nit: instead of key, let's pass in name, namespace and construct the key in here

**Review by steeling — APPROVED** [review]
2 quick comments but awesome work!

File: pkg/k8s/client.go (hunk 12 above)
Comment (allenlsy) [reply pkg/k8s/client.go:581]: I just noticed that the caller of this method uses a `types.NamespacedName` obj, which is k8s native object. So it should be fine to pass the object to this method
