### PR TITLE
Fix flaky e2e tests

### LINKED ISSUE #4843: e2e_hashivault_test.go occasionally fails in CI
**Bug description**:
The e2e_hashivault_test.go has become flaky in the CI after recent changes to certificate management.

This test is failing in the CI occasionally. The most recent failure on `main` is captured in https://github.com/openservicemesh/osm/actions/runs/2544748359
Logs: https://github.com/openservicemesh/osm/actions/runs/2544748359#artifacts

**Affected area (please mark with X where applicable)**:
- Certificate Management     [X]
- Tests                      [X]

### PR DESCRIPTION
**Pull request by keithmattix**
Signed-off-by: Keith Mattix II <keithmattix2@gmail.com>

**Description**:
Fixes flaky e2e test behavior observed in CI
Fixes #4843

**Testing done**:
Local e2e testing and multiple CI runs to validate that flakiness has ceased

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| Tests                      | [X] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

2. Is this a breaking change?

3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)?

### CODE REVIEW

File: tests/e2e/e2e_retry_policy_test.go [hunk 1]
```diff
@@ -125,6 +125,7 @@ var _ = OSMDescribe("Test Retry Policy",
 
 					By("A request that will be retried NumRetries times then fail")
 					err = wait.Poll(time.Second*3, time.Second*30, func() (bool, error) {
+						defer GinkgoRecover()
```
Comment (jaellio) [inline tests/e2e/e2e_retry_policy_test.go:128]: For my own understanding, should `GinkgoRecover()` be added to all `wait.Poll`s?

Comment (keithmattix) [reply tests/e2e/e2e_retry_policy_test.go:128]: Yeah I'm just playing around at this point. My dev machine is crawling, so I'm pushing to a PR branch for (more) rapid iteration

Comment (jaellio) [reply tests/e2e/e2e_retry_policy_test.go:128]: Got it!!

File: pkg/certificate/manager.go [hunk 2]
```diff
@@ -129,15 +129,23 @@ func (m *Manager) handleMRCEvent(mrcClient MRCClient, event MRCEvent) error {
...
 		case mrc.Status.State == constants.MRCStateActive:
+			m.mu.Lock()
 			m.signingIssuer = c
 			m.validatingIssuer = c
+			m.mu.Unlock()
 		case mrc.Status.State == constants.MRCStateIssuingRollback || mrc.Status.State == constants.MRCStateIssuingRollout:
+			m.mu.Lock()
 			m.signingIssuer = c
+			m.mu.Unlock()
 		case mrc.Status.State == constants.MRCStateValidatingRollback || mrc.Status.State == constants.MRCStateValidatingRollout:
```
Comment (jaellio) [inline pkg/certificate/manager.go:140]: I believe if a MRC is in a state of IssuingRollback it should only be used for validating.  I define the IssuingRollback state as the rollback of using this issuer to sign certificates.
```suggestion
		case mrc.Status.State == constants.MRCStateIssuingRollback || mrc.Status.State == constants.MRCStateValidatingRollout:
```

File: pkg/certificate/manager.go [hunk 3]
```diff
@@ -17,14 +17,14 @@ import (
 )
 
 // NewManager creates a new CertificateManager with the passed MRCClient and options
-func NewManager(ctx context.Context, mrcClient MRCClient, getServiceCertValidityPeriod func() time.Duration, getIngressCertValidityDuration func() time.Duration, msgBroker *messaging.Broker, checkInterval time.Duration) (*Manager, error) {
+func NewManager(ctx context.Context, mrcClient MRCClient, getServiceCertValidityPeriod func() time.Duration, getIngressCertValidityDuration func() time.Duration, msgBroker *messaging.Broker, checkInterval time.Duration, ns string) (*Manager, error) {
```
Comment (nojnhuh) [inline pkg/certificate/manager.go:20]: I'm not sure I see where `ns` is ultimately being used. Can it be removed?

File: pkg/k8s/informers/informers.go [hunk 4]
```diff
@@ -86,12 +86,16 @@ func WithSMIClients(smiTrafficSplitClient smiTrafficSplitClient.Interface, smiTr
 }
 
 // WithConfigClient sets the config client for the InformerCollection
-func WithConfigClient(configClient configClientset.Interface) InformerCollectionOption {
+func WithConfigClient(configClient configClientset.Interface, meshConfigName, osmNamespace string) InformerCollectionOption {
 	return func(ic *InformerCollection) {
-		informerFactory := configInformers.NewSharedInformerFactory(configClient, DefaultKubeEventResyncInterval)
+		listOption := configInformers.WithTweakListOptions(func(opt *metav1.ListOptions) {
+			opt.FieldSelector = fields.OneTermEqualSelector(metav1.ObjectNameField, meshConfigName).String()
```
Comment (jaellio) [inline pkg/k8s/informers/informers.go:92]: @nojnhuh Did we try to use a field selector for the MeshConfig in the past? I thought we decided against it for some reason/bug

File: pkg/certificate/manager.go [hunk 5]
```diff
@@ -49,7 +49,7 @@ func (m *Manager) startRotationTicker(ctx context.Context, checkInterval time.Du
 	}()
 }
 
-func (m *Manager) start(ctx context.Context, mrcClient MRCClient) error {
+func (m *Manager) start(ctx context.Context, mrcClient MRCClient, ns string) error {
```
[the remark this answers is not in the document]
Comment (keithmattix) [reply pkg/certificate/manager.go:52]: Ah, missed this in cleanup. Good catch!

File: pkg/k8s/informers/informers.go (hunk 4 above)
Comment (keithmattix) [reply pkg/k8s/informers/informers.go:92]: FWIW, copied the field selector from the [configurator client](https://github.com/openservicemesh/osm/blob/v1.1.1/pkg/configurator/client.go#L30) in v1.1.1

File: pkg/certificate/manager.go (hunk 3 above)
Comment (keithmattix) [reply pkg/certificate/manager.go:20]: Yep, it's cruft

File: pkg/certificate/manager.go (hunk 2 above)
Comment (jaellio) [reply pkg/certificate/manager.go:140]: The IssuingRollback state is set when an MRC enters the issuingRollout state. I don't think there should ever be a case where MRCs have the IssuingRollback and ValidatingRollout states.

Comment (jaellio) [reply pkg/certificate/manager.go:140]: This comment is not blocking and can be addressed in a follow up PR.

File: pkg/k8s/informers/informers.go (hunk 4 above)
Comment (nojnhuh) [reply pkg/k8s/informers/informers.go:92]: I vaguely remember something coming up about field selectors, but I don't think it was this. It worked here as expected as far as I remember.

**Review by jaellio — APPROVED** [review]

File: pkg/certificate/manager.go (hunk 2 above)
Comment (keithmattix) [reply pkg/certificate/manager.go:140]: Hmmm so what does it mean of one MRC is active, and the other is ValidatingRollout? Keep in mind that the control plane could restart between status updates of two different MRCs

**Comment by jaellio** [comment]
@keithmattix Could you please update the PR description and include any testing you have done?

**Review by nojnhuh — APPROVED** [review]
