### PR TITLE
fix(install): clean up resources when install fails

### LINKED ISSUE #1530: Clean up resources if Helm installation fails
**Bug description**:
If helm installation fails, resources are not cleaned up such as clusterrolebindings etc. We are left with a half-deployed state.
**Affected area (please mark with X where applicable)**:
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:
If install fails, the cluster should be as it was pre-installation
**Steps to reproduce the bug (as precisely as possible)**:
TBD
**How was OSM installed?**:
TBD
**Anything else we need to know?**:
TBD
**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

### PR DESCRIPTION
**Pull request by nojnhuh**
**Description**:
This change adds the behavior of the `--atomic` flag to our invocation
of `helm install` in the `osm install` command. With `--atomic`, Helm
will uninstall the release if it fails to install. `--atomic` also
implies `--wait` which will wait for pods, pod workloads, services,
PVCs, and CRDs to become ready before exiting.

A `--timeout` flag is also added to control the maximum amount of time
to wait for the resources to install and become ready. Its value is
passed through to Helm and behaves exactly the same as the `--timeout`
flag for `helm install`.

Fixes #1530

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [X]
- Control Plane          [ ]
- CLI Tool               [X]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

### CODE REVIEW

File: cmd/cli/install.go [hunk 1]
```diff
@@ -160,6 +161,7 @@ func newInstallCmd(config *helm.Configuration, out io.Writer) *cobra.Command {
 	f.BoolVar(&inst.deployJaeger, "deploy-jaeger", true, "Deploy Jaeger in the namespace of the OSM controller")
 	f.StringVar(&inst.envoyLogLevel, "envoy-log-level", "error", "Envoy log level is used to specify the level of logs collected from envoy and needs to be one of these (trace, debug, info, warning, warn, error, critical, off)")
 	f.BoolVar(&inst.enforceSingleMesh, "enforce-single-mesh", false, "Enforce only deploying one mesh in the cluster")
+	f.DurationVar(&inst.timeout, "timeout", 5*time.Minute, "time to wait for installation and resources in a ready state, zero means no timeout")
```
Comment (ksubrmnn) [inline cmd/cli/install.go:164]: Can you capitalize the description to match the others? Or lowercase the others, whichever is standard

**Review by ksubrmnn — CHANGES_REQUESTED** [review]
One nit, otherwise great change!

File: cmd/cli/install.go (hunk 1 above)
Comment (shashankram) [reply cmd/cli/install.go:164]: I think we need to follow a convention in the cli help text for flags. I noticed this inconsistency as well across cli commands.

File: tests/e2e/common.go [hunk 2]
```diff
@@ -425,7 +426,7 @@ func (td *OsmTestData) InstallOSM(instOpts InstallOSMOpts) error {
 		return errors.Wrap(err, "failed to run osm install")
 	}
 
-	return td.WaitForPodsRunningReady(td.osmNamespace, 90*time.Second, 1)
+	return nil
```
Comment (eduser25) [inline tests/e2e/common.go:429]: With this we are not checking if OSM actually came up. I'd be good to have the test fail here if OSM does not come up (ie. ErrPullImage) instead of later when we expect the applications or traffic to happen, which will be misleading when debugging.

Also not saying current implementation is best (as, if there are other containers in the NS, this check doesn't really work), but it did work in most circumstances.

Comment (nojnhuh) [reply tests/e2e/common.go:429]: We are checking that the osm-controller pod is running, but it's now checked by Helm during `osm install` before that command exits, making this wait in the framework redundant. Any extra wait calls for pods in the osm-system namespace in the individual tests are also made redundant by this change.

**Review by ksubrmnn — APPROVED** [review]

**Review by shashankram — APPROVED** [review]
