### PR TITLE
certificate/rotation: correctly rotate certs

### LINKED ISSUE #2786: Certificate rotation is broken
**Bug description**:
Certificate rotation is broken after changes made to the event notification mechanism. Rotated certificates are not pushed to concerned proxies upon rotation.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [X]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:
When certificates are rotated, updated certificates need to be pushed to relevant proxies.

### PR DESCRIPTION
**Pull request by shashankram**
**Description**:
Certificates are not being rotated as expected
because the channel on which they are making
announcements is no longer used and had been
dropped in favor of the pub-sub messaging infra.

This change fixes cert rotation as follows:
1. Uses the pub-sub model to publish cert rotation
   events when a cert corresponding to a given CN
   is rotated.
2. Updates the certificates stored in Envoy for those
   proxies whose identity matches the CN being rotated.

Verified that updated certs are correctly pushed to
proxies with this change.

Resolves #2786

Signed-off-by: Shashank Ram <shashr2204@gmail.com>

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [ ]
- Certificate Management [X]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
`No`

### CODE REVIEW

File: pkg/certificate/providers/certmanager/certificate_manager.go [hunk 1]
```diff
@@ -89,7 +90,12 @@ func (cm *CertManager) RotateCertificate(cn certificate.CommonName) (certificate
 	oldCert := cm.cache[cn]
 	cm.cache[cn] = newCert
 	cm.cacheLock.Unlock()
-	cm.announcements <- announcements.Announcement{}
+
+	events.GetPubSubInstance().Publish(events.PubSubMessage{
+		AnnouncementType: announcements.CertificateRotated,
+		NewObj:           cn,
+		OldObj:           cn,
+	})
```
Comment (eduser25) [inline pkg/certificate/providers/certmanager/certificate_manager.go:98]: For logging, one day could be useful to expose them both? or are we expecting a security concern here
```suggestion
		AnnouncementType: announcements.CertificateRotated,
		NewObj:           newCert,
		OldObj:           oldCert,
	})
```

**Review by eduser25 — APPROVED** [review]

**Review by snehachhabria — APPROVED** [review]

**Review by draychev — APPROVED** [review]

**Review by eduser25 — APPROVED** [review]
