### PR TITLE
xdslogs, fix race when multiple verticals write in xdslog map

### LINKED ISSUE #2441: Race condition in multiple map writes
Unprotected xdsLog map `newAggregatedDiscoveryResponse` can cause multiple writes on the same map by multiple XDS streams.

```
if s.enableDebug {
	if _, ok := s.xdsLog[proxy.GetCertificateCommonName()]; !ok {
		s.xdsLog[proxy.GetCertificateCommonName()] = make(map[envoy.TypeURI][]time.Time)
	}
	s.xdsLog[proxy.GetCertificateCommonName()][typeURL] = append(s.xdsLog[proxy.GetCertificateCommonName()][typeURL], time.Now())
}
```

```
{"level":"warn","component":"envoy/ads","time":"2021-02-03T00:24:34Z","file":"stream.go:29","message":"Envoy with certificate SerialNumber=47958120135765980282011679423970448229 connected"}
{"level":"warn","component":"envoy/ads","time":"2021-02-03T00:24:34Z","file":"stream.go:29","message":"Envoy with certificate SerialNumber=292599240870444999781775540991616545771 connected"}
{"level":"warn","component":"envoy/ads","time":"2021-02-03T00:24:34Z","file":"stream.go:29","message":"Envoy with certificate SerialNumber=13976008947031965673617590686339049877 connected"}
{"level":"warn","component":"envoy/ads","time":"2021-02-03T00:24:34Z","file":"stream.go:29","message":"Envoy with certificate SerialNumber=325617134786043019829286577548510098552 connected"}
{"level":"warn","component":"envoy/ads","time":"2021-02-03T00:24:34Z","file":"stream.go:29","message":"Envoy with certificate SerialNumber=309609523710001943616120577866357811376 connected"}
fatal error: concurrent map writes

goroutine 786 [running]:
runtime.throw(0x1d48b66, 0x15)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0041bde68 sp=0xc0041bde38 pc=0x434ad2
runtime.mapassign_faststr(0x1a2edc0, 0xc0042a8360, 0xc003e17980, 0x38, 0x307b100)
        /usr/local/go/src/runtime/map_faststr.go:211 +0x3f7 fp=0xc0041bded0 sp=0xc0041bde68 pc=0x413657
github.com/openservicemesh/osm/pkg/envoy/ads.(*Server).newAggregatedDiscoveryResponse(0xc003851020, 0xc003ed9500, 0xc000826e00, 0x208a8a0, 0xc0002ebef0, 0x3, 0xc003ee3920, 0xbffe99308f637c36)
        /home/eserra/src/osm/pkg/envoy/ads/response.go:136 +0xa6d fp=0xc0041be248 sp=0xc0041bded0 pc=0x182edad
github.com/openservicemesh/osm/pkg/envoy/ads.(*Server).sendTypeResponse(0xc003851020, 0x1d84958, 0x33, 0xc003ed9500, 0xc001cce4b0, 0xc000826e00, 0x208a8a0, 0xc0002ebef0, 0x0, 0x0)
        /home/eserra/src/osm/pkg/envoy/ads/response.go:30 +0x402 fp=0xc0041be730 sp=0xc0041be248 pc=0x182cab2
github.com/openservicemesh/osm/pkg/envoy/ads.(*Server).StreamAggregatedResources(0xc003851020, 0x207ce40, 0xc001cce4a0, 0x0, 0x0)
        /home/eserra/src/osm/pkg/envoy/ads/stream.go:164 +0x200b fp=0xc0041bfc18 sp=0xc0041be730 pc=0x183126b
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1bfb8c0, 0xc003851020, 0x2074920, 0xc0009e1d40, 0x3079530, 0xc00437c500)
        /home/eserra/src/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.9.8/envoy/service/discovery/v3/ads.pb.go:298 +0xad fp=0xc0041bfc60 sp=0xc0041bfc18 pc=0x16f00fd
google.golang.org/grpc.(*Server).processStreamingRPC(0xc003b18c00, 0x2081d60, 0xc003efe780, 0xc00437c500, 0xc0042a8b10, 0x302e820, 0x0, 0x0, 0x0)
        /home/eserra/src/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1237 +0xcd1 fp=0xc0041bfe38 sp=0xc0041bfc60 pc=0x16dd5f1
google.golang.org/grpc.(*Server).handleStream(0xc003b18c00, 0x2081d60, 0xc003efe780, 0xc00437c500, 0x0)
        /home/eserra/src/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1317 +0xcd6 fp=0xc0041bff68 sp=0xc0041bfe38 pc=0x16dee26
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000e2d830, 0xc003b18c00, 0x2081d60, 0xc003efe780, 0xc00437c500)
        /home/eserra/src/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:722 +0xa1 fp=0xc0041bffb8 sp=0xc0041bff68 pc=0x16ebac1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0041bffc0 sp=0xc0041bffb8 pc=0x467691
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/eserra/src/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:720 +0xa1
```

**Bug description**:

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

### PR DESCRIPTION
**Pull request by eduser25**
There is a race when multiple envoys are connecting at the same time, where
multiple writes can happen on the xdslog map.
Although rare, it's easy to hit with a beefier setup with more pods, or specially
when OSM restarts (since all pods will attempt to connect mostly at the same time).

- For now this is gated with a simple mutex. If this introduces unwanted penalties
we could discuss dropping all this in-memory logging and have regular logging do
the job instead.
- Also limited the number of logs we can store at a time per proxy (before
 had no upper limit)
- A copy of the map is now handed to debugger, to avoid read/write concurrent
accesses on the map.

Fixes #2441

Signed-off-by: Eduard Serra <eduser25@gmail.com>

**Affected area**:

- Control Plane          [x]

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

### CODE REVIEW

File: pkg/envoy/ads/debugger.go [hunk 1]
```diff
@@ -3,11 +3,24 @@ package ads
...
+
 	"github.com/openservicemesh/osm/pkg/certificate"
 	"github.com/openservicemesh/osm/pkg/envoy"
 )
 
 // GetXDSLog implements XDSDebugger interface and a log of the XDS responses sent to Envoy proxies.
-func (s Server) GetXDSLog() *map[certificate.CommonName]map[envoy.TypeURI][]time.Time {
-	return &s.xdsLog
+func (s *Server) GetXDSLog() *map[certificate.CommonName]map[envoy.TypeURI][]time.Time {
+	var logsCopy map[certificate.CommonName]map[envoy.TypeURI][]time.Time
```
Comment (shashankram) [inline pkg/envoy/ads/debugger.go:14]: 👀

File: pkg/envoy/ads/debugger.go [hunk 2]
```diff
@@ -3,11 +3,24 @@ package ads
...
+	var err error
+
+	s.withXdsLogMutex(func() {
+		err = copier.Copy(&logsCopy, &s.xdsLog)
+	})
```
Comment (shashankram) [inline pkg/envoy/ads/debugger.go:19]: Could you drop a comment here on why this needs to be protected.

File: pkg/envoy/ads/profile.go [hunk 3]
```diff
@@ -19,3 +26,23 @@ func xdsPathTimeTrack(t time.Time, tURIStr string, commonNameStr string, success
 		WithLabelValues(tURIStr, fmt.Sprintf("%t", *success)).
 		Observe(elapsed.Seconds())
 }
+
+func (s *Server) trackXdsLog(cn certificate.CommonName, typeURL envoy.TypeURI) {
```
Comment (shashankram) [inline pkg/envoy/ads/profile.go:30]:
```suggestion
func (s *Server) trackXDSLog(cn certificate.CommonName, typeURL envoy.TypeURI) {
```

**Review by snehachhabria — APPROVED** [review]

**Review by draychev — CHANGES_REQUESTED** [review]
Could we use Go channels instead?

**Comment by eduser25** [comment]
@draychev could you be a bit more descriptive? I'd take channels anytime for inter-routine comms, but not to prevent multiple routines access the same resource. what's your idea?

**Review by draychev — APPROVED** [review]
@eduser25 thanks for the fix - I understand this is needed asap.

**Comment by eduser25** [comment]
Talked with Del, we might revisit this as we would like to avoid mutexes (though some sort of serialization cannot be avoided with current state of affairs) in favour of something else (channels?)

Double checking perf impact of the mutex and will merge after.
