### PR TITLE
ads: do not handle empty URI

### LINKED ISSUE #3258: XDS state machine results in continuous looping when updated listeners are yet to drain
**Bug description**:
With recent changes to the XDS state machine `pkg/envoy/ads/stream.go`, there is a scenario where the XDS state machine can enter in a continuous loop of requesting RDS resources referenced in a stale listener that has not yet been drained. The default drain interval is 600s (10 minutes), which means when a listener is updated to remove previously set RDS references, Envoy will continuously request for this resource till the older listener configuration is completely drained.

Such a scenario arises for ingress (and egress in the future) configurations where the filter chains referencing route configurations can be added and removed dynamically based on policies applied to the cluster. When a policy is removed and the corresponding listener is updated, Envoy continuously requests for stale RDS resources which no longer can be generated because of the absence of corresponding policies.

This issue proposes to update the default drain interval from 600s to 5s, so listeners are drained as soon as possible upon reconfiguration so that Envoy stops requesting stale resources while the listeners are being drained. Additionally, a default deny filter_chain could be necessary on the listener to account for cases where there are no filter chains on the listener (no service filter chains + no egress filter chain + no ingress filter chain), otherwise, the updated LDS response will exclude the listener which will require supporting unsubscriptions for resources in the XDS state machine.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

### PR DESCRIPTION
**Pull request by eduser25**
- Renames `Wildcard` to `EmptyURI` to avoid naming overlap with xDS
"wildcard" mode for a given URI.
- Avoid handling Empty URI as some of the logic needs some work for
it to be properly handled.

We will revisit this after further exploration.

Fixes #3258

Signed-off-by: edu <eduser25@gmail.com>

- Control Plane          [x]

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

### CODE REVIEW

File: pkg/envoy/types.go [hunk 1]
```diff
@@ -24,20 +23,16 @@ func (t TypeURI) String() string {
...
 func (t TypeURI) Short() string {
-	if t == TypeWildcard {
-		return Wildcard
-	}
-	return utils.GetLastChunkOfSlashed(t.String())
+	return XDSShortURINames[t]
 }
 
 // IsWildcard returns true when the TypeURI is the one requesting ALL discovery types.
 func (t TypeURI) IsWildcard() bool {
```
Comment (shashankram) [inline pkg/envoy/types.go:30]:
```suggestion
func (t TypeURI) IsEmptyTypeURI() bool {
```

File: pkg/envoy/types.go [hunk 2]
```diff
@@ -24,20 +23,16 @@ func (t TypeURI) String() string {
...
-	return t == TypeWildcard
+	return t == TypeEmptyURI
 }
 
 // ValidURI defines valid URIs
 var ValidURI = map[string]TypeURI{
-	string(TypeWildcard):           TypeWildcard,
```
Comment (shashankram) [inline pkg/envoy/types.go:40]: Removing empty typeURI results in error logs, which is not correct per these changes:
```
{"level":"error","component":"envoy/ads","time":"2021-04-30T16:44:57Z","file":"stream.go:174","message":"Proxy SerialNumber=136867002654723736450590910962478278124 PodUID=a9d0fb42-e2ce-4596-a3aa-92631baeb4ce: Unknown/Unsupported URI: "}
```

File: pkg/envoy/types.go (hunk 1 above)
Comment (eduser25) [reply pkg/envoy/types.go:30]: :+1:

File: pkg/envoy/types.go (hunk 2 above)
Comment (eduser25) [reply pkg/envoy/types.go:40]: I will instead, allow `emptyUrl` as valid, but add a check just right after to skip empty url with debug log instead

**Review by shashankram — APPROVED** [review]

**Review by snehachhabria — APPROVED** [review]
