### PR TITLE
fix(cli): Add missing flags for upgrade

### LINKED ISSUE #2651: Update mesh upgrade cli command with missing osm-config ConfigMap keys
**Bug description**:
Some keys in the ConfigMap that can be updated such as `outbound_ip_range_exclusion_list` and `enable_privileged_init_container` are missing in this cli command.

Full list of supported ConfigMap keys are as follows:
https://github.com/openservicemesh/osm/blob/ecb1a8414667ec674c6a9b1af26b6c6d64c418c5/pkg/configurator/client.go#L20-L59

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

### PR DESCRIPTION
**Pull request by nojnhuh**
**Description**:
This change updates the `osm mesh upgrade` command with two additional
flags mapping to fields recently added to the osm-config ConfigMap:

`--outbound-ip-range-exclusion-list`

`--enable-privileged-init-container`

Fixes #2651

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [X]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

### CODE REVIEW

**Review by snehachhabria — APPROVED** [review]

**Review by michelleN — CHANGES_REQUESTED** [review]
Would be nice to add a small test for this change if possible.

File: cmd/cli/mesh_upgrade.go [hunk 1]
```diff
@@ -142,6 +149,8 @@ func newMeshUpgradeCmd(config *helm.Configuration, out io.Writer) *cobra.Command
 	f.StringVar(&upg.tracingAddress, "tracing-address", "", "Tracing server hostname")
 	f.Uint16Var(&upg.tracingPort, "tracing-port", 0, "Tracing server port")
 	f.StringVar(&upg.tracingEndpoint, "tracing-endpoint", "", "Tracing server endpoint")
+	f.StringSliceVar(&upg.outboundIPRangeExclusionList, "outbound-ip-range-exclusion-list", nil, "A global list of IP ranges to exclude from outbound traffic interception by the sidecar proxy. Pass once per IP range or a single comma-separated value.")
```
Comment (shashankram) [inline cmd/cli/mesh_upgrade.go:152]:
```suggestion
	f.StringSliceVar(&upg.outboundIPRangeExclusionList, "outbound-ip-range-exclusion-list", nil, "A global list of IP ranges to exclude from outbound traffic interception by the sidecar proxy. Pass once per IP range or a single comma separated list of IP ranges of the form a.b.c.d/x")
```

**Review by shashankram — APPROVED** [review]

**Review by michelleN — APPROVED** [review]
